### ISSUE TITLE
The tutorials must be able to have syntaxes that can be converted to rst.

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit-tutorials#1000]
For example, the generated docs for the pulse tutorials (https://qiskit.org/documentation/tutorials/pulse/2_building_pulse_instructions.html#Building-Pulse-Instructions)
![image](https://user-images.githubusercontent.com/11485594/89846039-243b0080-db4e-11ea-840b-ce147e5fa44e.png)

- Sphinx doesn't support \`\`literal\`\` emphasizing within external hyperlinks. For example ```Delay(duration: int, channel)`` <#delay>`__

- We also might want to figure out how internal hyperlinks can be used interchangeably in both the tutorials and sphinx generated docs. Because "#delay" adds hyperlink in .ipynb/markdown but it doesn't do the same when converted to .rst.

**Comment by divshacker** [comment]
Hey @SooluThomas  I think this is fixed. You can close this issue

**Comment by Eric-Arellano** [comment]
It's possible to use RST with notebooks: https://nbsphinx.readthedocs.io/en/0.5.0/raw-cells.html
