### ISSUE TITLE
Pulse Simulator missing in the High Perfomance simulators tutorial on qiskit tutorials

### ISSUE THREAD

**Issue by charmerDark** [Qiskit/qiskit-tutorials#1002]
The issue can be seen on the page linked here: https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html
The code block clearly shows Pulse Simulator as one of the available simulators. However, no mention of it was made throughout the article. While it may be out of the scope of that particular tutorial, I believe at least a mention of the simulator must be included in tutorial.  A link to the tutorial for the pulse simulator might also be very helpful.  Attaching link of said tutorial too. https://qiskit.org/documentation/tutorials/pulse/8_pulse_simulator_backend_model.html
Attaching a screenshot for reference.

![image](https://user-images.githubusercontent.com/49775559/89923332-0d63df00-dc1e-11ea-9f46-73aabfde0128.png)

**Comment by divshacker** [comment]
Hey @charmerDark  I think in the new version of this notebook they have't define each of the back ends but shown the new different available options for some backends. And I think now it is not necessary to add pulse simulator content in this tutorial. Correct me if I am wrong. 
Thank you

**Comment by Eric-Arellano** [comment]
In addition to what @divshacker explains, the Aer tutorials now live in https://github.com/Qiskit/qiskit-aer. We're archiving this repository very soon and moving the remaining tutorials to qiskit-terra, so I'm going to close this as stale.

Thanks for the suggestion on how to improve Qiskit!
