### ISSUE TITLE
Typo in README.md file 

### ISSUE THREAD

**Issue by brunormzg** [Qiskit/qiskit-tutorials#1013]
I suspect there is a typo within the README.md file, under the Contribution Guidelines section. 

<img width="861" alt="Captura de Pantalla 2020-08-12 a la(s) 16 50 03" src="https://user-images.githubusercontent.com/47431792/90071892-02f82280-dcbc-11ea-8deb-013835158a36.png">

Isn't the appropriate word for this sentence "expected"?

**Comment by SooluThomas** [comment]
Fixed in #1021
