### ISSUE TITLE
noise - 3_measurement_error_mitigation.ipynb has deprecation warnings

### ISSUE THREAD

**Issue by ShellyGarion** [Qiskit/qiskit-tutorials#1024]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Recently the measurement mitigation notebook was updated to also include VQE and now it has deprecation warnings in it due to Aqua in cell 36:
`result = vqe.run(qi_noise_model_qasm)`

yields deprecation warnings:

/home/computertreker/git/qiskit/qiskit-tutorial/foo/lib/python3.8/site-packages/qiskit/aqua/operators/state_fns/dict_state_fn.py:207: DeprecationWarning: The Python built-in `round` is deprecated for complex scalars, and will raise a `TypeError` in a future release. Use `np.round` or `scalar.round` instead.

### Steps to reproduce the problem
See cell 36 in:
`https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/noise/3_measurement_error_mitigation.ipynb`

**Comment by woodsp-ibm** [comment]
The version that is checked in was run under the prior release = 0.19.6. If you look here https://qiskit.org/documentation/tutorials/noise/3_measurement_error_mitigation.html you can see it run under qiskit 0.20.0, that has the latest Aqua, where the code was altered to take care of the deprecation. The notebook version that is checked in just needs re-running against the newest release.
