### ISSUE TITLE
Typo in 4_randomized_benchmarking.po file

### ISSUE THREAD

**Issue by gilbion** [Qiskit/qiskit-tutorials#1034]
The original (English) text in the following link has "wee" instead of "we".

https://crowdin.com/translate/qiskit-docs/9138/en-ptbr?filter=basic&value=5

Documentation link: https://qiskit.org/documentation/tutorials/noise/4_randomized_benchmarking.html

1) Select the Parameters of the RB Run

First, wee need to choose the following parameters:

**Comment by tgag17** [comment]
Hi! Can I make the necessary changes?

**Comment by gilbion** [comment]
sure!

**Comment by SooluThomas** [comment]
Fixed in #1040
