### ISSUE TITLE
QSVM on multiclass Classification

### ISSUE THREAD

**Issue by KillerStrike17** [Qiskit/qiskit-tutorials#1038]
### What is the expected behavior?

I was not able to find tutorial on QSVM on multiclass classfication..  It would be awesome if any working tutorial be added

**Comment by javabster** [comment]
Hi thanks for your interest and apologies for the slow response! We are currently in the process of reorganising the Qiskit Tutorials, archiving this repo and moving the existing tutorials to the main qiskit repo or other appropriate projects. During this transition we will be focusing on maintaining/improving our existing content and are not able to take submissions for brand new tutorials at this time

Thanks anyway for your feedback and helping us make Qiskit better! 🚀
