### ISSUE TITLE
Deprecation warning in the linear_systems_of_equations.ipynb

### ISSUE THREAD

**Issue by coleparadis** [Qiskit/qiskit-tutorials#1039]
### Informations

- **Qiskit version**: 0.21.0
- **Python version**: 3.7.3
- **Operating system**: MacOS

### What is the current behavior?
When running the program, many of the block have deprecation warnings based on the fact that QuantumCircuits are not being used.

### Steps to reproduce the problem
Run linear_systems_of_equations.ipynb

### What is the expected behavior?
The expected behavior is to not produce errors related to deprecation.

### Suggested solutions
Convert the data types to use QuantumCircuits rather than the deprecated data types.

**Comment by MartinBeseda** [comment]
Dear @coleparadis ,
 I could have a look at this, if it remains uncorrected.

**Comment by coleparadis** [comment]
Martin,

I am no longer working on this project so I am unsure if the issue is still
applicable or not, I left it alone after December of 2020.

Thanks,
Cole

**Comment by Eric-Arellano** [comment]
This tutorial no longer exists in this repo.
