### ISSUE TITLE
Inconsistencies in rendering docs vs. Jupyter notebooks (Qiskit Optimization)

### ISSUE THREAD

**Issue by Travis-S-IBM** [Qiskit/qiskit-tutorials#1042]
This issue points out some places where information (mostly text) is rendered inconsistently between the docs on qiskit.org/documentation and the corresponding Jupyter notebooks which generate the pages.

1 [Quadratic Program](https://qiskit.org/documentation/tutorials/optimization/1_quadratic_program.html)
* Above cell 13, the list of substitutions gets inlined.

2 [Converters for Quadratic Programs](https://qiskit.org/documentation/tutorials/optimization/2_converters_for_quadratic_programs.html)
* The list of converters in the opening paragraphs gets inlined.

3 [Minimum Eigen Optimizer](https://qiskit.org/documentation/tutorials/optimization/3_minimum_eigen_optimizer.html)
* The list of MinimumEigenSolvers in the opening paragraphs gets inlined.
* The hyperlinks for references 1 and 2 are not rendered correctly.

4 [Grover Optimizer](https://qiskit.org/documentation/tutorials/optimization/4_grover_optimizer.html)
* The hyperlink for reference 1 is not rendered correctly.

5 [ADMM Optimizer](https://qiskit.org/documentation/tutorials/optimization/5_admm_optimizer.html)
* The hyperlinks for references 1 and 2 are not rendered correctly.
* The list of solvers just under cell 1 gets inlined.

6 [Max-Cut and Traveling Salesman Problem](https://qiskit.org/documentation/tutorials/optimization/6_examples_max_cut_and_tsp.html)
* The steps listed in the 2nd paragraph of section _Approximate Universal Quantum Computing for Optimization Problems_ are inlined.
* The references above Cell 2 are inlined.

7 [Vehicle routing](https://qiskit.org/documentation/tutorials/optimization/7_examples_vehicle_routing.html)
* The list just above Cell 9 gets inlined.

**Comment by Travis-S-IBM** [comment]
@nonhermitian Who would be the person to work with to figure out why these inconsistencies happen?

**Comment by nonhermitian** [comment]
Limitations number four in the readme might help.

**Comment by Travis-S-IBM** [comment]
@nonhermitian How so? There's no math in these lists....

Is there a doc somewhere that outlines how the rendering as RST files works?

**Comment by nonhermitian** [comment]
Ok, I guess I misunderstood the issues.  Here is a link to the conversion program docs:

https://nbsphinx.readthedocs.io/en/0.7.1/

In short, Sphinx parsing is much more strict than that allowed in Jupyter notebooks.  This is why you are seeing what you do.

**Comment by mtreinish** [comment]
It's worth pointing out the actual rst generation is done using pandoc (at least until https://github.com/spatialaudio/nbsphinx/issues/36 is implemented). Basically nbsphinx runs `nbconvert` on the notebook to generate a markdown file then runs pandoc on that markdown output to generate restructured text which is what gets passed to sphinx for building the html version. The pandoc conversion is where I expect this is going wrong, there are a lot of edge cases there and pandoc doesn't always know what a renderer is looking for.

**Comment by nonhermitian** [comment]
Closing as (kind of) solved.  Can reopen if otherwise.

**Comment by shil-m** [comment]
> Ok, I guess I misunderstood the issues. Here is a link to the conversion program docs:
> 
> https://nbsphinx.readthedocs.io/en/0.7.1/
> 
> In short, Sphinx parsing is much more strict than that allowed in Jupyter notebooks. This is why you are seeing what you do.

Has this been fixed? Because the documentation is still inconsistent for 6 [Max-Cut and Traveling Salesman Problem](https://qiskit.org/documentation/tutorials/optimization/6_examples_max_cut_and_tsp.html#Max-Cut-and-Traveling-Salesman-Problem)
