### ISSUE TITLE
Variational Quantum Regression

### ISSUE THREAD

**Issue by clearya1** [Qiskit/qiskit-tutorials#1043]
Hi there! I am not 100% sure if this is the right place to put this, but if not, could somebody please redirect me to the appropriate channels? 

Over the summer, I wrote an algorithm which performs polynomial regression using the Qiskit software. The algorithm is a variational one, in that it computes a cost function using quantum hardware, coupled with classical optimisers. This work was inspired by the section 4.2.1 of the Qiskit textbook. 

I was thinking that this work might be a nice addition to the textbook under the Implementations of Recent Quantum Algorithms section (4.2), so I created a Jupyter notebook similar to the Qiskit textbook style. Everything can be found at this repo: [VQR](https://github.com/clearya1/Variational-Quantum-Regression.git)

### What is the expected behavior?

This algorithm takes two data sets - an independent data set (x) and dependent data set (y) and attempts to return the line of best fit for an n-th order polynomial. The inputs to the algorithm are the data sets (x & y) and the polynomial order (n).

**Comment by aasfaw** [comment]
hi -- please submit a pull request here: http://github.com/qiskit-community/qiskit-textbook

**Comment by nonhermitian** [comment]
Closing as textbook content
