### ISSUE TITLE
Arbitrary State Preparation

### ISSUE THREAD

**Issue by Abduhu** [Qiskit/qiskit-tutorials#1049]
I would like to know how to extract elementary gates from Initialize class? 
The initialization of the state does not show that. I tried to extract basic gates by using 'Instruction.definition' and 'QuantumCircuit.data'. However, every time, I get same circuit which is far away from being the right one (very low fidelity).

**Comment by divshacker** [comment]
Hey @Abduhu I think can be best answered in slack please try to ask this in slack. If Already answered then please close this issue

**Comment by divshacker** [comment]
@nonhermitian
