### ISSUE TITLE
Unused variable in 02_gradients_framework.ipynb

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-tutorials#1073]
In input line 11, `hessian_coeffs` is defined, but is nowhere used.

Version information
qiskit-tutorials  4e122b4

**Comment by divshacker** [comment]
Can I work on this .

**Comment by divshacker** [comment]
......

**Comment by divshacker** [comment]
Done!
Please check the PR @jlapeyre

**Comment by jlapeyre** [comment]
Thank you @divshacker !
