### ISSUE TITLE
6_examples_max_cut_and_tsp  Typesetting Bug

### ISSUE THREAD

**Issue by leonox** [Qiskit/qiskit-tutorials#1078]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?
https://qiskit.org/documentation/tutorials/optimization/6_examples_max_cut_and_tsp.html

- What is the current text that needs to be fixed or removed? (You can copy and paste)
"The algorithm works as follows:
Choose the wi and wij in the target Ising problem. In principle, even higher powers of Z are allowed.
Choose the depth of the quantum circuit m. Note that the depth can be modified adaptively.
Choose a set of controls θ and make a trial function |ψ(θ)⟩, built using a quantum circuit made of C-Phase gates and single-qubit Y rotations, parameterized by the components of θ.
Evaluate
C(θ)=⟨ψ(θ) |H| ψ(θ)⟩=∑iwi⟨ψ(θ) |Zi| ψ(θ)⟩+∑i<jwij⟨ψ(θ) |ZiZj| ψ(θ)⟩bysamplingtheoutcomeofthecircuitintheZ−basisandaddingtheexpectationvaluesoftheindividualIsingtermstogether.Ingeneral,differentcontrolpointsaround:math:‘θ‘havetobeestimated,dependingontheclassicaloptimizerchosen.
"
The text is in math environment, likely reason: additional "$"?

**Comment by divshacker** [comment]
Hey @leonox I think this bug is fix now.

**Comment by Eric-Arellano** [comment]
Sounds like this was fixed. Either way, the tutorial no longer lives in this repository.
