### ISSUE TITLE
Typo in the chemistry tutorial 01_electronic_structure

### ISSUE THREAD

**Issue by wmurphy-collabstar** [Qiskit/qiskit-tutorials#1083]
### Informations

- **Qiskit version**: 0.23.0
- **Python version**: 3.8.3
- **Operating system**: macOS Catalina

### What is the current behavior?
There is a typo in the first paragraph. The word "electronc" should be changed to "electrons".
I tried to make a pull request for it but the tests didn't pass when I did so.

### Steps to reproduce the problem
Already discussed above.

### What is the expected behavior?
Already discussed above.

### Suggested solutions
Already discussed above.

**Comment by wmurphy-collabstar** [comment]
I know this is a very small issue, but is there someone that has time to work on it? Again, I tried to make a pull request for it, but the tests didn't pass.

If anyone is looking for a good first issue, please feel free to claim it.

**Comment by danchepkwony** [comment]
I'll claim it!

**Comment by wmurphy-collabstar** [comment]
Great, thank you!

**Comment by SooluThomas** [comment]
Fixed in #1090
