### ISSUE TITLE
AttributeError in the optimization tutorials 01_quadratic_program and 05_admm_optimizer.

### ISSUE THREAD

**Issue by wmurphy-collabstar** [Qiskit/qiskit-tutorials#1084]
### Informations

- **Qiskit version**: 0.23.0
- **Python version**: 3.8.3
- **Operating system**: macOS Catalina

### What is the current behavior?
When trying to run the optimization notebooks 01_quadratic_program and 05_admm_optimizer, it results in a error message "AttributeError: 'BinaryVarType' object has no attribute 'one_letter_symbol'".

### Steps to reproduce the problem
Open either notebook in the Quantum Lab of IBM Quantum Experience, click on Kernel, and then the option Restart & Run All. Then, the third cell in 01_quadratic_program and 05_admm_optimizer produces the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-693bde9f8a8c> in <module>
     14 # load quadratic program from docplex model
     15 qp = QuadraticProgram()
---> 16 qp.from_docplex(mdl)
     17 print(qp.export_as_lp_string())

/opt/conda/lib/python3.7/site-packages/qiskit/optimization/problems/quadratic_program.py in from_docplex(self, model)
    561         var_names = {}
    562         for x in model.iter_variables():
--> 563             if x.get_vartype().one_letter_symbol() == 'C':
    564                 x_new = self.continuous_var(x.lb, x.ub, x.name)
    565             elif x.get_vartype().one_letter_symbol() == 'B':

AttributeError: 'BinaryVarType' object has no attribute 'one_letter_symbol'

### What is the expected behavior?
The expected behavior is no error, that both notebooks run all cells and produce the expected output.

### Suggested solutions
Probably fix the input given to the call qp.from_docplex(mdl), but otherwise I'm not sure.

**Comment by nonhermitian** [comment]
This is a known issue and fixed in the release that just went out

**Comment by wmurphy-collabstar** [comment]
Okay, thank you for the update. I'll close the issue now.
