### ISSUE TITLE
Typo in the algorithm tutorial 1 "01_algorithm_introduction"

### ISSUE THREAD

**Issue by schulta** [Qiskit/qiskit-tutorials#1095]
### What is the current behavior?
There is a typo in [01_algorithm_introduction.ipynb](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/01_algorithms_introduction.ipynb)
It is at the last of the paragraph right after 5th code cell;
"... for the specific chemistry problem being solved. which it has to do the same thing."

### Suggested solutions
Modify the sentence as below;
"... for the specific chemistry problem being solved, which it has to do the same thing."

Or simply delete the last part as below;
"... for the specific chemistry problem being solved."

**Comment by bvnger** [comment]
I'd like to work on this fix , as it would help me practice with pull requests and working on issues. What are the best resources for learning to do this properly?

**Comment by SooluThomas** [comment]
This should have been fixed by https://github.com/Qiskit/qiskit-tutorials/pull/1096. Please reopen if the issue still persists.
