### ISSUE TITLE
LinAlgError: Schur form not found. Possibly ill-conditioned. in one for the tutorial

### ISSUE THREAD

**Issue by KillerStrike17** [Qiskit/qiskit-tutorials#1104]
### Informations

- **Qiskit version**: 0.23.2
- **Python version**: 3.7
- **Operating system**: Windows

### What is the current behavior?

Gives and error for T1/T2 thermal relaxation

### Steps to reproduce the problem
run this tutorial 
https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/simulators/3_building_noise_models.ipynb
in numpy version 1.19.3 and Qiskit terra version 0.16.1

### What is the expected behavior?

The tutorial should run.. but gives a LinAlgError: Schur form not found. Possibly ill-conditioned. error

**Comment by divshacker** [comment]
Hey it is running without any error in IBM Quantum Experience. Check this https://quantum-computing.ibm.com/jupyter/tutorial/simulators/3_building_noise_models.ipynb
There might be problem locally in your system

**Comment by Eric-Arellano** [comment]
Closing as likely fixed, based on @divshacker, and either way probably stale. Please feel free to reopen in https://github.com/Qiskit/qiskit-aer if still relevant.
