### ISSUE TITLE
Chemistry - 05_Sampling_potential_energy_surface - errors in text

### ISSUE THREAD

**Issue by Feigenbaum4669** [Qiskit/qiskit-tutorials#1124]
In the Extrapolation section:
"In practice, the user sets the window by specifies" - should be "by specifying" ;
"which also the number of previous points" - should be (???) "which is also the number of previous points"

**Comment by divshacker** [comment]
@Feigenbaum4669 Hey I have tried to fix this please let me know if any more changes required

**Comment by Feigenbaum4669** [comment]
Issue closed
