### ISSUE TITLE
Syntax issue after the tutorials are rendered by Sphinx

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit-tutorials#1128]
1. The operators tutorial when rendered to sphinx isn't working well. (https://qiskit.org/documentation/tutorials/operators/01_operator_flow.html)

   <img width="583" alt="image" src="https://user-images.githubusercontent.com/11485594/107369185-733b0180-6aaf-11eb-8493-e14360af70b4.png">

2. https://qiskit.org/documentation/tutorials/circuits_advanced/09_pulse_simulator_duffing_model.html#Section-3:-Duffing-oscillator-model
   
   <img width="904" alt="image" src="https://user-images.githubusercontent.com/11485594/109678102-4d51cb80-7b48-11eb-837d-ef1e6f871c56.png">

3. https://qiskit.org/documentation/tutorials/noise/9_entanglement_verification.html
   
   <img width="914" alt="image" src="https://user-images.githubusercontent.com/11485594/109681788-d4547300-7b4b-11eb-9b65-074f77db0c1e.png">

4. https://qiskit.org/documentation/tutorials/operators/02_gradients_framework.html

   <img width="930" alt="image" src="https://user-images.githubusercontent.com/11485594/109682773-bafff680-7b4c-11eb-8840-9b513747b3e9.png">

**Comment by divshacker** [comment]
Hey @bopardikarsoham try to fix this issue. If you want to contribute.

**Comment by bopardikarsoham** [comment]
Thanks for suggesting @divshacker!

**Comment by nonhermitian** [comment]
Some of this is fixed in #1150
