### ISSUE TITLE
Missing icons in tutorials pages

### ISSUE THREAD

**Issue by beckykd** [Qiskit/qiskit-tutorials#1129]
These two pages are missing icons:

missing icon for vehicle routing https://qiskit.org/documentation/tutorials/optimization/index.html
missing icon https://qiskit.org/documentation/tutorials/machine_learning/index.html

**Comment by bopardikarsoham** [comment]
Hey @beckykd I want to work on this issue. Do you have the image icons or should I add them according to my own choice?

**Comment by beckykd** [comment]
Hi! I don't have icons.  I just noticed that they are missing.  Thanks!

**Comment by shil-m** [comment]
Hey @bopardikarsoham! Are you still working on this?

**Comment by bopardikarsoham** [comment]
Yup @shil-m actually I had performed a PR but had to delete it due to system issues. Now, my system is ok so I will work on it. Do you want to say something @shil-m ?

**Comment by shil-m** [comment]
@bopardikarsoham Not really, I was thinking I could give it a shot if it is still unresolved. Pl go ahead.

**Comment by Eric-Arellano** [comment]
Any tutorials without dedicated icons now use the Qiskit logo as the default:

https://github.com/Qiskit/qiskit-tutorials/blob/55b1e23dc8b778eab4c03501daa45007c5425ecb/conf.py#L47
