### ISSUE TITLE
PauliSumOp is not treated in the operator (opflow) tutorial

### ISSUE THREAD

**Issue by jlapeyre** [Qiskit/qiskit-tutorials#1130]
The opflow tutorial (in this folder)

https://github.com/Qiskit/qiskit-tutorials/tree/master/tutorials/operators

should include a discussion of PaulSumOp

### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

**Comment by woodsp-ibm** [comment]
This has only just been added and not yet released yet. But yes for the refactored opflow tutorials, based on the opflow now being in Terra for the next release, it would be good to include this in there along with other function such as the Z2Symmetry

**Comment by jlapeyre** [comment]
opflow will be deprecated soon. And no one has jumped on this yet. I think it's safe to close this issue.
