### ISSUE TITLE
Chemistry - 01_Electronic_Structure - include Jordan-Wigner derivation

### ISSUE THREAD

**Issue by kaelynj** [Qiskit/qiskit-tutorials#1132]
The first tutorial in the chemistry section ([https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/chemistry/01_electronic_structure.ipynb](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/chemistry/01_electronic_structure.ipynb)) introduces the Hartree-Fock state and the molecular Hamiltonian with a brief mention of several qubit mappings that are available, including the Jordan-Wigner (JW) transformation.

I think it would be worth it to add in more sections going over how these mappings are derived.  If the community thinks this would be worth it, I have a [repo](https://github.com/kaelynj/Qiskit-HubbardModel/) containing a section explicitly going over the JW transformation which I can make a pull request for.  

If need be, I'd also be willing to write in sections for the Bravyi-Kitaev mappings as well.

**Comment by woodsp-ibm** [comment]
Hi, I am wondering whether this might be more the sort of material that is more suitable for the Qiskit Textbook at  https://qiskit.org/textbook/preface.html It sounds more like theory etc behind this with maybe some code example illustrating how its done. The textbook has some chemistry material in there now and maybe could be expanded upon to include some fundamentals like this.

@pbark @aasfaw Any thoughts?

**Comment by aasfaw** [comment]
Agree with @woodsp-ibm -- this is likely a nice entry under the quantum chemistry modules. @kaelynj thanks for this. @frankharkins can help you integrate with the qiskit textbook showing both JW and BK. The github repo for the textbook is at https://github.com/qiskit-community/qiskit-textbook and gets rendered at https://qiskit.org/textbook

**Comment by kaelynj** [comment]
Wonderful, glad I can help!  It may also be worth it to point to an issue request I made on the subject at the qiskit-textbook repo. [https://github.com/qiskit-community/qiskit-textbook/issues/924](https://github.com/qiskit-community/qiskit-textbook/issues/924)  I think there might be room to make two separate sections here.  One under section 3 to introduce quantum simulation generally, and another piece in section 4.2 to go over the JW transform.  What are everyone's thoughts?

**Comment by pbark** [comment]
@woodsp-ibm I fully agree with the point you raise here. @kaelynj  thanks a lot for thinking of it. @aasfaw We already had some preliminary discussion with @frankharkins about this and I think it makes sense that we include also the rest of the tutorials related to chemistry in the qiskit textbook  chapters.

**Comment by Eric-Arellano** [comment]
The chemistry tutorials no longer live in this repository, so closing as stale.
