### ISSUE TITLE
Getting 404 for start_here.ipynb  Advanced Circuit, Finance, and Pulse links

### ISSUE THREAD

**Issue by LaeticiaW** [Qiskit/qiskit-tutorials#1143]
Getting 404 for start_here.ipynb  Advanced Circuit, Finance, and Pulse links

**Comment by divshacker** [comment]
Doing

**Comment by divshacker** [comment]
Please check this PR and let me know any changes needed. @LaeticiaW 
Thank You.

**Comment by divshacker** [comment]
Hey @SooluThomas @LaeticiaW  This issue can be closed as The bug is Fixed now.
