### ISSUE TITLE
Wrong noise model for RB Sequence with T1,T2 Errors in RB tutorial

### ISSUE THREAD

**Issue by pdc-quantum** [Qiskit/qiskit-tutorials#1146]
### Informations

- **Qiskit version**: 0.23.0
- **Python version**: 3.8.1
- **Operating system**: Windows

### What is the current behavior?

Wrong noise model at compilation  for RB Sequence with T1,T2 Errors

### Steps to reproduce the problem

in the " Run an RB Sequence with T1,T2 Errors" section:
run cell with code:
job = qiskit.execute(rb_circ_transpile, noise_model=noise_model, shots=shots, backend=backend, backend_options={'max_parallel_experiments': 0})

### What is the expected behavior?

Obtain a  RBFitter object corresponding to noise_model2

### Suggested solutions

replace code by:

job = qiskit.execute(rb_circ_transpile, noise_model=noise_model2, shots=shots, backend=backend, max_parallel_experiments=0)

This will in addition eliminate the warning:
<ipython-input-20-83f1adaa196a>:10: DeprecationWarning: Using `backend_options` kwarg has been deprecated as of qiskit-aer 0.7.0 and will be removed no earlier than 3 months from that release date. Runtime backend options should now be added directly using kwargs for each option.

**Comment by pdc-quantum** [comment]
Further in the notebook I see also:
gates_per_cliff = rb.rb_utils.gates_per_clifford(transpile_list2,xdata[0],basis_gates,rb_opts2['rb_pattern'][0])

Isn't:  ,xdata2[0] instead of ,xdata[0]_ ?

**Comment by Eric-Arellano** [comment]
Pardon that this didn't get more attention sooner. The `noise` tutorials no longer live in this repository so I'll close this as stale.
