### ISSUE TITLE
Incorrect equation for the Hamiltonian in Max Cut

### ISSUE THREAD

**Issue by camitava0321** [Qiskit/qiskit-tutorials#1148]
## Incorrect equation for the Hamiltonian in Max Cut
- While going through MaxCut documentation, I noticed a possible mistake while formulating C(Z) from C(X) - if x-> (1-z)/2 then (1-x) should be just z/2, not (1+z). If this is so then the Hamiltonian will eventually be different. Also after C(Z) the const term is being rendered as latex code.
- https://qiskit.org/documentation/tutorials/optimization/6_examples_max_cut_and_tsp.html
![image](https://user-images.githubusercontent.com/25051480/93669671-693e4500-fab3-11ea-9a12-0a2b0fd20f91.png)

**Comment by shil-m** [comment]
@camitava0321 , if x->(1-z)/2, then (1-x)->(1+z)/2 . I think the equation seems correct as there is /4 in the denominator. However the latex code needs to be looked into. @Claeb101  Are you still working on this, if not I would like to.

**Comment by Claeb101** [comment]
@shil-m Sure you can work on this!

**Comment by ElePT** [comment]
Hi, thanks for your interest and apologies for the slow response! the code referred to in this issue belongs to qiskit-optimization: https://github.com/qiskit-community/qiskit-optimization. We are now focusing on archiving this repository and moving its contents to the relevant projects. If you think this issue persists, I encourage you to open the issue directly in qiskit-optimization. 

Thanks anyway for your feedback and helping us make Qiskit better! 🚀
