### ISSUE TITLE
correction in theory section of vehicle routing tutorial

### ISSUE THREAD

**Issue by arunvellat** [Qiskit/qiskit-tutorials#1164]
### Informations

- **Qiskit version**: NA
- **Python version**: NA
- **Operating system**: NA

### What is the current behavior?
In the tutorial on vehicle routing,  I see a couple of issues:
1. n is used inconsistently - in the initial explanation, n is the number of clients, and hence number of nodes is n+1, while in the code n is the total number of nodes.
2. The quadratic program form, does not have definitions for vectors v and e. Also, the first term in the expression for A is incorrect.

### Suggested solutions

It would be nice to have the derivation of the quadratic form from the integer programming formulation of the problem.

**Comment by woodsp-ibm** [comment]
The tutorials that are here on optimization have been moved to the new qiskit-optimization repo and refactored. These here will shortly be removed. So the vehicle routing one is here now https://github.com/Qiskit/qiskit-optimization/blob/master/docs/tutorials/07_examples_vehicle_routing.ipynb having been updated too. I do not know if the issue you state still exists - maybe you'd take a look. If this still exists then maybe @nonhermitian can transfer this over.

**Comment by Eric-Arellano** [comment]
Closing as the tutorials no longer exist here. Thanks for suggesting how to improve Qiskit!
