### ISSUE TITLE
tcirc not used

### ISSUE THREAD

**Issue by iuliazidaru** [Qiskit/qiskit-tutorials#1167]
### Informations

- **Qiskit version**: 0.25.0
- **Python version**: 3.8.9 (default, Apr 8 2021, 12:01:33) [GCC 9.3.0]
- **Operating system**: Linux

### What is the current behavior?
https://qiskit.org/documentation/tutorials/simulators/7_matrix_product_state_method.html

### Steps to reproduce the problem
Run find tcirc. We can see 3 lines: `tcirc = transpile(circ, simulator)`
tcirc is never used.

### What is the expected behavior?
No unused variables.

### Suggested solutions
Probably on the next line the simulator should run the transpiled circuit: 
`result = simulator.run(tcirc).result()`

**Comment by divshacker** [comment]
Yeah I think it is a small typo of not using `tcirc` It haven't  showed any error because `circ` is already defined and have not any problem with the code.  Thanks for Pointing out. I am now making PR for this
