### ISSUE TITLE
Tutorials should not use get_statevector

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-tutorials#1177]
`result.get_statevector` belongs to the old Aer interface, where we had separate qasm and statevector simulators. With the move to Aer 0.8, the instruction `save_statevector` was correctly added to the tutorials, but the call to `get_statevector` is still there.

**Comment by Agnij-Moitra** [comment]
Could please you share the link of that file?

**Comment by MartinBeseda** [comment]
@yaelbh I could take a look at it, if the tutorials aren't fixed yet.

**Comment by yaelbh** [comment]
Ok, thanks. I'm not absolutely sure if the issue is correct. @chriseclectic or @mtreinish will probably know.

**Comment by Eric-Arellano** [comment]
The API still exists as of Qiskit 0.44. So this should be fine. https://qiskit.org/documentation/stubs/qiskit.result.Result.html#qiskit.result.Result.get_statevector
