### ISSUE TITLE
Qiskit for multiple architectures tutorial missing

### ISSUE THREAD

**Issue by tanujkhattar** [Qiskit/qiskit-tutorials#1182]
https://www.ibm.com/blogs/research/2019/11/qiskit-for-multiple-architectures/ blog post points to https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/advanced/terra/7_different_qubit_technologies.ipynb for the code related to the tutorial. However, the second link returns a 404 not found error. 

The link on the original blog post should be updated. I'm also not able to find the [different_qubit_technologies.ipynb](https://github.com/Qiskit/qiskit-tutorials/search?q=different_qubit_technologies.ipynb)  tutorial in the repository. Does the tutorial still exist?

**Comment by divshacker** [comment]
Hey @tanujkhattar  I think tutorial might get deleted in these recent versions. If you want that specific tutorial then [here](https://github.com/Qiskit/qiskit-tutorials/blob/6da1d4681dbe772fb1b4a6a832c24a1cf31d3f4f/qiskit/advanced/terra/7_different_qubit_technologies.ipynb) is the link

**Comment by javabster** [comment]
Closing this issue as it seems OP has a solution for their original issue
