### ISSUE TITLE
404 when clicking on "IBM Quantum Lab" from tutorials note

### ISSUE THREAD

**Issue by apupier** [Qiskit/qiskit-tutorials#1184]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### Steps to reproduce the problem

For instance, 
- https://qiskit.org/documentation/tutorials/circuits/1_getting_started_with_qiskit.html
- Click on IBM Quantum Lab link (which is pointing to https://quantum-computing.ibm.com/jupyter/tutorial/circuits/1_getting_started_with_qiskit.ipynb ) 
- redirection fgoes to https://quantum-computing.ibm.com/lab/files/qiskit-tutorials/tutorials/circuits/1_getting_started_with_qiskit.ipynb
- 
![Screenshot from 2021-05-21 10-07-35](https://user-images.githubusercontent.com/1105127/119104378-7a619c00-ba1c-11eb-9cdf-7259aa1bbcdc.png)

### What is the expected behavior?

No 404, and the correct filme opened and ready to be launched

### workaround
- Follow link above in the "note panel" "this page was generated from".
- click on raw
- right-click save as
- Go to IBM Quantum Lab, click on "Upload File", select the saved as file

**Comment by divshacker** [comment]
I think it is now fixed

**Comment by apupier** [comment]
The problem still occurs to me

**Comment by divshacker** [comment]
> The problem still occurs to me

Yes that's why I said. If you put this problem on slack then it would more helpful for you because many people are not facing any problem.

**Comment by rupeshknn** [comment]
so the actual file in IBM Quantum Lab is located at 
https://quantum-computing.ibm.com/lab/files/qiskit-tutorials/**qiskit**/tutorials/circuits/1_getting_started_with_qiskit.ipynb

but the links in the tutorials point to
https://quantum-computing.ibm.com/lab/files/qiskit-tutorials/tutorials/circuits/1_getting_started_with_qiskit.ipynb

the possible corrections could either be in the location of the files in IBM QLAB or corrections can be made to the links

**Comment by nonhermitian** [comment]
The links have been removed because it was impossible to keep the tutorials in sync with the quantum lab.
