### ISSUE TITLE
use 'density matrix' instead of 'state matrix' in the plotting tutorial

### ISSUE THREAD

**Issue by eliarbel** [Qiskit/qiskit-tutorials#1189]
the tutorials/circuits/2_plotting_data_in_qiskit.html tutorial uses 'state matrix' when talking about `plot_state_city` and `plot_state_hinton`. I think it's better to use 'density matrix' instead; the documentation of those methods also uses density matrix

**Comment by fs1132429** [comment]
i would like to contribute to this

**Comment by shil-m** [comment]
Hi @fs1132429, I didn't notice you commented you wanted to work on it, I read the issue earlier but made the PR later without commenting here. I am still figuring out the policies in GitHub. I am not sure what could be done in this case, should I close my PR? @eliarbel Any comments?

**Comment by eliarbel** [comment]
PR #1196 should suffice, thanks a lot
