### ISSUE TITLE
array_to_latex function

### ISSUE THREAD

**Issue by VedDharkar** [Qiskit/qiskit-tutorials#1192]
Suggestion:- In the 01_circuit_basics.ipynb when representing latex form of the quantum state there are 2 ways that are 
1. `state.draw('latex')  # This one is described in the notebook`
 2. `array_to_latex(state)`  
I think both the ways should be described. The learner should also know the alternate piece of code

**Comment by divshacker** [comment]
Hey @VedDharkar  I made a PR regarding your Issue. Let me know if it fixes your issue or not.

**Comment by VedDharkar** [comment]
> Hey @VedDharkar I made a PR regarding your Issue. Let me know if it fixes your issue or not.

Thank You! I will let you know.
