### ISSUE TITLE
Two copies of each image in Transpiler Passes and Pass Manager documentation

### ISSUE THREAD

**Issue by singhmeet11** [Qiskit/qiskit-tutorials#1199]
**Problem -** Each images is printed twice after executing `draw('mpl')` , in the tutorial for Transpiler Passes and Pass Manager. 
**Possible Solution -** Look at the discussion in the issue number 1265 of Qiskit, the Author also faced a similar issue and there seems to be a possible solution there. 
![Capture1](https://user-images.githubusercontent.com/76438148/121801690-3a29be00-cc56-11eb-8b16-955ac2c2a575.PNG)

**Comment by divshacker** [comment]
May I work on this issue or you want to take it  @singhmeet11 ?

**Comment by divshacker** [comment]
If possible we can extend this fix in other tutorials too. @nonhermitian

**Comment by singhmeet11** [comment]
@divshacker I don't think the moderators will have a problem with us fixing the two images problem. Let me create a new issue for solving this issue in the few tutorials that have the same problem. Then we can correct this
