### ISSUE TITLE
Typo in gradient_framework tutorial

### ISSUE THREAD

**Issue by zxiaac** [Qiskit/qiskit-tutorials#1214]
Problem: 
In this file: qiskit-tutorials/tutorials/operators/02_gradients_framework.ipynb, in the paramter-shift section, there is an extra 'partial' symbol in the formula.  
![qiskitTypo](https://user-images.githubusercontent.com/30754238/124377547-fb2fdb00-dcde-11eb-9213-ff12251e54d3.PNG)

**Comment by divshacker** [comment]
Hey @zxiaac may I work on this issue ?
