### ISSUE TITLE
SWAP test tutorial

### ISSUE THREAD

**Issue by darshkaushik** [Qiskit/qiskit-tutorials#1228]
### What is the expected behavior?
SWAP test is a classic example in quantum computing which can be used as base to example various functionalities in qiskit. I would like to contribute a tutorial with visuals on bloch sphere on how we can use qiskit to find how much do two states differ.

**Comment by darshkaushik** [comment]
This tutorial currently has some py scripts for util functions to avoid much cluttering and to show how one can make functions using qiskit. It also has some images with annotations for better explanation as I struggled when I was learning it due to lack of visualizations. 

Would highly appreciate if any of the reviewers can review the pull request #1205.

**Comment by javabster** [comment]
Hi thanks for your interest and apologies for the slow response! We are currently in the process of reorganising the Qiskit Tutorials, archiving this repo and moving the existing tutorials to the main qiskit repo or other appropriate projects. During this transition we will be focusing on maintaining/improving our existing content and are not able to take submissions for brand new tutorials at this time

Thanks anyway for your feedback and helping us make Qiskit better! 🚀
