### ISSUE TITLE
A mistranslation in the Japanese Tutorial

### ISSUE THREAD

**Issue by massn** [Qiskit/qiskit-tutorials#1247]
Hi!
I found a mistranslation in https://qiskit.org/documentation/locale/ja_JP/tutorials/noise/8_tomography.html#%EF%BC%91%E9%87%8F%E5%AD%90%E3%83%93%E3%83%83%E3%83%88%E3%81%AE%E7%8A%B6%E6%85%8B%E3%83%88%E3%83%A2%E3%82%B0%E3%83%A9%E3%83%95%E3%82%A3%E3%83%BC%E3%81%AE%E4%BE%8B .
`１量子ビットの状態トモグラフィーの例` (= a translation of `1-qubit process tomography example`)  must be `１量子ビットのプロセストモグラフィーの例`.
How should I correct it?

**Comment by Eric-Arellano** [comment]
Hi! Sorry that we never replied to this. Thank you for reporting it! That's a big help.

It looks like this tutorial no longer exists. But for the future, FYI that translations are handled in the https://github.com/qiskit-community/qiskit-translations repository.
