### ISSUE TITLE
CompleteMeasFitter loses track of qubit labels and state ordering

### ISSUE THREAD

**Issue by YWang92** [Qiskit/qiskit-tutorials#1249]
### Informations

- **Qiskit version**:  
-qiskit-terra | 0.18.2
qiskit-aer | 0.9.0
qiskit-ignis | 0.6.0
qiskit-ibmq-provider | 0.16.0
qiskit-aqua | 0.9.5
qiskit | 0.30.0
- **Python version**:  3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
- **Operating system**:  Linux

### What is the current behavior?
In qiskit.ignis.mitigation.measurement,  the function complete_meas_cal  sometimes unexpectedly relabel the qubits and state order can be unexpectedly reversed.

### Steps to reproduce the problem
**1. The returned qubits are relabled as 0, 1, 2**:
`qr = qiskit.QuantumRegister(5)
qubit_list = [2,3,4]
meas_calibs, state_labels = complete_meas_cal(qubit_list=qubit_list, qr=qr, circlabel='mcal')

backend = qiskit.Aer.get_backend('qasm_simulator')
job = qiskit.execute(meas_calibs, backend=backend, shots=1000)
cal_results = job.result()
meas_fitter = CompleteMeasFitter(cal_results, state_labels, circlabel='mcal')
for i in meas_fitter.qubit_list:
    print(i)`

**2.The state order of the qubits can be reversed after executing CompleteMeasFitter**:

`qr = qiskit.QuantumRegister(5)
qubit_list = [4,1]
meas_calibs, state_labels = complete_meas_cal(qubit_list=qubit_list, qr=qr, circlabel='mcal')

noise_model = noise.NoiseModel()
for qi in range(5):
    if qi == qubit_list[0]:
        read_err = noise.errors.readout_error.ReadoutError([[0.5, 0.5],[0.5,0.5]])
        noise_model.add_readout_error(read_err, [qi])
    elif qi == qubit_list[1]:
        read_err = noise.errors.readout_error.ReadoutError([[1, 0],[0,1]])
        noise_model.add_readout_error(read_err, [qi])

backend = qiskit.Aer.get_backend('qasm_simulator')
job = qiskit.execute(meas_calibs, backend=backend, shots=1000, noise_model=noise_model)
cal_results = job.result()

meas_fitter = CompleteMeasFitter(cal_results, state_labels, qubit_list=qubit_list, circlabel='mcal')

print(meas_fitter.cal_matrix)

for i in meas_fitter.qubit_list:
    meas_fitter_sub = meas_fitter.subset_fitter(qubit_sublist=[i])
    print("q",i)
    print( meas_fitter_sub.cal_matrix)
`

### What is the expected behavior?
The returned qubit_list of meas_fitter should always be the same as the one put into the function complete_meas_cal.

**Comment by Eric-Arellano** [comment]
Hi, pardon that this didn't get a response sooner! Thank you for the feedback.

The code for CompleteMeasFitter now lives in Qiskit, rather than Qiskit Ignis: https://qiskit.org/documentation/stubs/qiskit.utils.mitigation.CompleteMeasFitter.html. It looks like the function you're referring to doesn't exist anymore. Further, this class is deprecated and will be removed soon.

So, I'm going to close this as no longer relevant since the functionality is being removed. Please feel free to reopen an issue at https://github.com/Qiskit/qiskit if you believe this is still an issue.
