### ISSUE TITLE
Update issue templates to latest one

### ISSUE THREAD

**Issue by divshacker** [Qiskit/qiskit-tutorials#1252]
GitHub has rolled out new issue forms for public repository.
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/
Please check this out.
I recently got to know about this Feature. It will be good if we implement this in this repository.

**Comment by orangekame3** [comment]
@HuangJunye 
Hi, if nobody has been assigned to this task, I'm interested in it.

**Comment by divshacker** [comment]
Yes, Feel free to work on this and Open a PR.

**Comment by Eric-Arellano** [comment]
This repository is being archived and the tutorials moved to Terra, so this is no longer relevant. Thanks for opening it!
