### ISSUE TITLE
dag_drawer(dag) throws FileNotFoundError: [Errno 2] "dot" not found in path. in  04_transpiler_passes_and_passmanager tutorial

### ISSUE THREAD

**Issue by oevers** [Qiskit/qiskit-tutorials#1257]
### Informations

- **Qiskit version**:
- <h3>Version Information</h3>

Qiskit Software | Version
-- | --
qiskit-terra | 0.18.3
qiskit-aer | 0.9.1
qiskit-ignis | 0.6.0
qiskit-ibmq-provider | 0.17.0
qiskit-aqua | 0.9.5
qiskit | 0.31.0
qiskit-nature | 0.2.2
qiskit-finance | 0.2.1
qiskit-optimization | 0.2.3
qiskit-machine-learning | 0.2.1

- **Python version**: 
Python | 3.8.12 (default, Oct 12 2021, 06:23:56)  [Clang 10.0.0 ]

- **Operating system**:
OS | Darwin
CPUs | 6
Memory (Gb) | 16.0
Tue Dec 28 21:35:49 2021 CET

### What is the current behavior?
Cell number 17 of the following tutorial
https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/04_transpiler_passes_and_passmanager.ipynb

Throws some nasty errors

### Steps to reproduce the problem
Run this notebook in a jupyter notebook (e.g. via anaconda)

cell number 17:
from qiskit.converters import circuit_to_dag
from qiskit.tools.visualization import dag_drawer
dag = circuit_to_dag(circ)
dag_drawer(dag)

the last statement throws an error:

> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> ~/opt/anaconda3/envs/qiskit_env/lib/python3.8/site-packages/pydot.py in create(self, prog, format, encoding)
>    1922         try:
> -> 1923             stdout_data, stderr_data, process = call_graphviz(
>    1924                 program=prog,
> 
> ~/opt/anaconda3/envs/qiskit_env/lib/python3.8/site-packages/pydot.py in call_graphviz(program, arguments, working_dir, **kwargs)
>     131 
> --> 132     process = subprocess.Popen(
>     133         program_with_args,
> 
> ~/opt/anaconda3/envs/qiskit_env/lib/python3.8/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
>     857 
> --> 858             self._execute_child(args, executable, preexec_fn, close_fds,
>     859                                 pass_fds, cwd, env,
> 
> ~/opt/anaconda3/envs/qiskit_env/lib/python3.8/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
>    1703                         err_msg = os.strerror(errno_num)
> -> 1704                     raise child_exception_type(errno_num, err_msg, err_filename)
>    1705                 raise child_exception_type(err_msg)
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'dot'
> 
> During handling of the above exception, another exception occurred:
> 
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-25-ba9060344f7d> in <module>
>       3 dag = circuit_to_dag(circ)
>       4 #(dag, scale=0.7, filename=None, style="color"):
> ----> 5 dag_drawer(dag)
> 
> ~/opt/anaconda3/envs/qiskit_env/lib/python3.8/site-packages/qiskit/visualization/dag_visualization.py in dag_drawer(dag, scale, filename, style)
>     179         with tempfile.TemporaryDirectory() as tmpdirname:
>     180             tmp_path = os.path.join(tmpdirname, "dag.png")
> --> 181             dot.write_png(tmp_path)
>     182             with Image.open(tmp_path) as test_image:
>     183                 image = test_image.copy()
> 
> ~/opt/anaconda3/envs/qiskit_env/lib/python3.8/site-packages/pydot.py in new_method(path, f, prog, encoding)
>    1741                     encoding=None):
>    1742                 """Refer to docstring of method `write.`"""
> -> 1743                 self.write(
>    1744                     path, format=f, prog=prog,
>    1745                     encoding=encoding)
> 
> ~/opt/anaconda3/envs/qiskit_env/lib/python3.8/site-packages/pydot.py in write(self, path, prog, format, encoding)
>    1826                 f.write(s)
>    1827         else:
> -> 1828             s = self.create(prog, format, encoding=encoding)
>    1829             with io.open(path, mode='wb') as f:
>    1830                 f.write(s)
> 
> ~/opt/anaconda3/envs/qiskit_env/lib/python3.8/site-packages/pydot.py in create(self, prog, format, encoding)
>    1931                 args[1] = '"{prog}" not found in path.'.format(
>    1932                     prog=prog)
> -> 1933                 raise OSError(*args)
>    1934             else:
>    1935                 raise
> 
> FileNotFoundError: [Errno 2] "dot" not found in path.

I get the same error when running the above (and the code that it prereqs) in a python shell, so not notebook or anaconda specific, at least not directly.

### What is the expected behavior?

should work without error

### Suggested solutions

instructions on how to get this work. I have a feeling this is a setup error of some sort, e.g. I did not have graphviz installed which I installed using pip install graphviz resulting in graphviz 0.19.1 being installed.

**Comment by iuliazidaru** [comment]
Looks similar to: https://github.com/Qiskit/qiskit-terra/issues/3099. I cannot reproduce the issue with qiskit.terra 0.19.1. The tutorial runs correctly.
Was there a filename present?

**Comment by oevers** [comment]
I just re-ran the tutorial with the following Version Info, so I can only presume that some other library is not at the right level.

I can reproduct the error with even the simplest circuit:
```
from qiskit.converters import circuit_to_dag
from qiskit.tools.visualization import dag_drawer
circ = QuantumCircuit(1)
dag = circuit_to_dag(circ)
dag_drawer(dag)

```

what are the versions of **pydot** and **graphviz** that you are using @iuliazidaru 

the pydot library tries t call graphviz with an argument of "dot"

```
        try:
            stdout_data, stderr_data, process = call_graphviz(
                program=prog,
                arguments=arguments,
                working_dir=tmp_dir,
            )
        except OSError as e:
            if e.errno == errno.ENOENT:
                args = list(e.args)
                args[1] = '"{prog}" not found in path.'.format(
                    prog=prog)
                raise OSError(*args)
            else:
                raise
```

resulting in the following

```
~/opt/anaconda3/envs/qiskit_env/lib/python3.8/site-packages/pydot.py in create(self, prog, format, encoding)
   1931                 args[1] = '"{prog}" not found in path.'.format(
   1932                     prog=prog)
-> 1933                 raise OSError(*args)
   1934             else:
   1935                 raise

```
<h3>Version Information</h3>

Qiskit Software | Version
-- | --
qiskit-terra | 0.19.1
qiskit-aer | 0.10.1
qiskit-ignis | 0.7.0
qiskit-ibmq-provider | 0.18.3
qiskit-aqua | 0.9.5
qiskit | 0.34.0
qiskit-nature | 0.2.2
qiskit-finance | 0.2.1
qiskit-optimization | 0.2.3
qiskit-machine-learning | 0.2.1

Python version | 3.8.12
Python compiler | Clang 10.0.0
Python build | default, Oct 12 2021 06:23:56
OS | Darwin
CPUs | 6
Memory (Gb) | 16.0
Thu Jan 20 14:27:42 2022 CET

**Comment by oevers** [comment]
I have:
pydot                   1.4.2
graphviz                0.19.1

**Comment by mtreinish** [comment]
You probably do not have graphviz installed. Graphviz is not a python program it's a standalone application (written in C) that can't be installed via pip or imported via python (the graphviz package on pypi that gets installed with `pip install graphviz` is a python binding library and not actually graphviz). The dag drawer is calling out to that external program to generate the visualization and the error you're hitting is because the `graphviz` executable can't be found. You can find instructions on how to install it here: https://www.graphviz.org/download/ for your particular platform. 

FWIW,  this requirement is documented in the function documentation: https://qiskit.org/documentation/stubs/qiskit.visualization.dag_drawer.html

**Comment by oevers** [comment]
oh that's embarrassing, you're absolutely right, I installed it with brew and now things are working. Closing this now.
