### ISSUE TITLE
tutorials/textbook/01_IQPE.ipynb code error

### ISSUE THREAD

**Issue by cribetti** [Qiskit/qiskit-tutorials#1263]
I believe there is an error with a line of code, given the description immediately before. In section:
https://qiskit.org/documentation/tutorials/textbook/01_IQPE.html#All-substeps-of-the-3rd-step
should the code entry
qc.p(-3*pi/2,0).c_if(c,3)
actually be
qc.p(-3*pi/4,0).c_if(c,3) ?

**Comment by Roshan-Thomas** [comment]
@cribetti yep it should be 3pi/4 and not 3pi/2. But it doesn't make any difference on the output, the final probabilities remains same 0.125 . Only the circuit will change

**Comment by Roshan-Thomas** [comment]
can i be assigned to update this on the docs?

**Comment by divshacker** [comment]
Feel free to open a PR and start working

**Comment by Roshan-Thomas** [comment]
Hi @divshacker, I have fixed the issue and did a PR but for some reason the builds failed 🤷🏼‍♂️. Could you help me out?

Apologies for tagging u to this.
