### ISSUE TITLE
Feature to create error for overrotation

### ISSUE THREAD

**Issue by anhdpham** [Qiskit/qiskit-tutorials#1264]
### What is the expected behavior?

I would like a feature to create overrotation error in quantum circuit

**Comment by ewinston** [comment]
This can be done by getting the schedules for the basis gates on your backend and e.g. modifying the pulse amplitudes away from their calibrated values. Would this work for you?

**Comment by javabster** [comment]
Hi thanks for your interest and apologies for the slow response! We are currently in the process of reorganising the Qiskit Tutorials, archiving this repo and moving the existing tutorials to the main qiskit repo or other appropriate projects. During this transition we will be focusing on maintaining/improving our existing content and are not able to take submissions for brand new tutorials at this time

Thanks anyway for your feedback and helping us make Qiskit better! 🚀
