### ISSUE TITLE
Circuits returning no noise

### ISSUE THREAD

**Issue by thesullivantage** [Qiskit/qiskit-tutorials#1295]
### Informations

- **Qiskit version**: 0.34.2
- **Python version**:  3.8.12
- **Operating system**: IBM Q Lab 

### What is the current behavior?
Using IBMQ Job Manager to aggregate a large number of circuit's return distributions for generating a data set to train on calculated fidelity. Circuits should return a histogram of outputted states, but only return 00000 as if there is hidden optimization happening.

The only gates used are H, Z, and CX, per the requirements of our project.

(Circuits all are themselves stacked with their mirror -> identity operator).

### Steps to reproduce the problem

https://lab.quantum-computing.ibm.com/user/613e46f9a0cb9e9e68502b7e/files/makeSandbox.ipynb?_xsrf=2%7Cbeb2ed83%7C26b9b9f0b99017a5cae99f01be202c8c%7C1646867007

- create many circuits concatenated with its mirror (IBMQJobManager)
- transpile it on some backed with optimization_level=0
- run circuits on the backend, all values in the bin for 00000

### What is the expected behavior?

Get a distribution of output states for each circuit - implying the presence of noise.

### Suggested solutions

Not sure.

**Comment by HuangJunye** [comment]
Sorry for the late reply. Could you please paste the code you used ? I do not have access to your file in the IBM Quantum Lab.
