### ISSUE TITLE
qiskit-tutorials/tutorials/circuits/3_summary_of_quantum_operations.ipynb cu3 & u2 are deprecated

### ISSUE THREAD

**Issue by WhiteSymmetry** [Qiskit/qiskit-tutorials#1314]
cu3 & u2 are deprecated:
1. The QuantumCircuit.u2 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You can use the general 1-qubit gate QuantumCircuit.u instead: u2(φ,λ) = u(π/2, φ, λ). Alternatively, you can decompose it interms of QuantumCircuit.p and QuantumCircuit.sx: u2(φ,λ) = p(π/2+φ) sx p(λ-π/2) (1 pulse on hardware). qc.u2(pi/2,pi/2,q)
2. The QuantumCircuit.cu3 method is deprecated as of 0.16.0. It will be removed no earlier than 3 months after the release date. You should use the QuantumCircuit.cu method instead, where cu3(ϴ,φ,λ) = cu(ϴ,φ,λ,0).
qc.cu3(pi/2, pi/2, pi/2, q[0], q[1])

**Comment by HuangJunye** [comment]
Thanks for reporting the issue. Yes, you are absolutely right u1, u2, u3 gates and the controlled versions of them have been deprecated. Would you mind creating a pull request to replace u1, u2, u3 gates with the more generic u gates in the tutorial? 

Please let me know if you are new to making open source contributions and will need some help!

**Comment by padraignix** [comment]
Took a stab at correcting the notebook. There were the two code blocks that were throwing the deprecation warnings, however there were also references to the deprecated gates in the verbiage as well. Those should have all been corrected with the PR.
