### ISSUE TITLE
Remove index page

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-tutorials#1315]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Each section in the tutorial page has its own index page showing up as an icon similar to the tutorials itself which is confusing.

### Steps to reproduce the problem

Go to https://qiskit.org/documentation/tutorials.html#quantum-circuits, click the last icon "circuit tutorials".

<img width="843" alt="image" src="https://user-images.githubusercontent.com/7631333/169010058-5de91fd2-3899-4e10-9888-7700a671d8f5.png">

It will lead to this page https://qiskit.org/documentation/tutorials/circuits/index.html which contain the same tutorials in the section but in its own page.

### What is the expected behavior?
Remove index page of each section in https://qiskit.org/documentation/tutorials.html

### Suggested solutions
Either remove index.rst in each folders of qiskit-tutorials repo or update the glob rule in [tutorials.rst](https://github.com/Qiskit/qiskit/blob/master/docs/tutorials.rst) in qiskit meta package

**Comment by mtreinish** [comment]
The index pages are required for building the tutorials in standalone docs builds. Without the index files for each section the tutorials will not be included in the toctree for the build. This will cause warnings which will be fatal in downstream builds (such as in qiskit component CI) and a docs build output where you can't navigate to the tutorials (assuming it builds them).

**Comment by HuangJunye** [comment]
I suspected that. Is it possible to exclude index.rst in the glob rules under each section in qiskit meta package repo?

**Comment by HuangJunye** [comment]
This PR https://github.com/Qiskit/qiskit-tutorials/pull/1234 tried to address this issue but it was put on hold. Let me investigate a bit further.
