### ISSUE TITLE
Rename `master` branch to `main` branch in this repo

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-tutorials#1316]
### What is the expected behavior?

Many (if not all) repos in qiskit github org has renamed `master` branch to `main` branch, we should do that in this repo as well. I am not sure about the implications and the steps to do that though.

Related to https://github.com/Qiskit/qiskit/issues/1493

**Comment by nandakishore1807** [comment]
I think it is not necessary to rename the branchs
