### ISSUE TITLE
Add `requirements-dev.txt` for local development

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-tutorials#1317]
### What is the expected behavior?

There is no `requirements-dev.txt` for this repo for local development and doc building.

**Comment by HuangJunye** [comment]
Some of the requirements are mentioned in README: https://github.com/Qiskit/qiskit-tutorials#building-documentation

**Comment by HuangJunye** [comment]
ipykernal is one of the requirement

**Comment by bopardikarsoham** [comment]
I would like to work on this issue @HuangJunye!

**Comment by HuangJunye** [comment]
Sure, that would be great! Please let me know if you need help @bopardikarsoham

**Comment by HuangJunye** [comment]
@bopardikarsoham I found a few files specified the requirements here: https://github.com/Qiskit/qiskit-tutorials/issues/1317#issuecomment-1129818689 that will probably useful to generate the requirements-dev.txt

**Comment by HuangJunye** [comment]
Not sure if [pipreqs](https://github.com/bndr/pipreqs) works well for this repo where most the codes are inside the notebooks, but you can investigate if you are interested.

**Comment by bopardikarsoham** [comment]
Yes, pipreqs does not work. There is a problem with unicode encoding.

**Comment by HuangJunye** [comment]
Closed by #1323
