### ISSUE TITLE
Cleanup `.gitignore`

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-tutorials#1318]
### What is the expected behavior?

Remove outdated files / folders in `.gitignore`: https://github.com/Qiskit/qiskit-tutorials/blob/master/.gitignore

https://github.com/Qiskit/qiskit-tutorials/blob/66ed39388e897062c97bc065ac29b5517c9a9468/.gitignore#L8-L11

https://github.com/Qiskit/qiskit-tutorials/blob/66ed39388e897062c97bc065ac29b5517c9a9468/.gitignore#L24-L26

~~Ignis is removed so this line is probably not applicable as well.~~ This file no longer exist.

https://github.com/Qiskit/qiskit-tutorials/blob/66ed39388e897062c97bc065ac29b5517c9a9468/.gitignore#L32

**Comment by SaumyaBhushan** [comment]
@HuangJunye added a pull request https://github.com/Qiskit/qiskit-tutorials/pull/1321 , please review
