### ISSUE TITLE
Update documentation building section on README

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-tutorials#1325]
Update documentation building section on README https://github.com/Qiskit/qiskit-tutorials#building-documentation with the newly added requirements-dev.txt https://github.com/Qiskit/qiskit-tutorials/pull/1323 and other non python dependencies (pandoc and graphviz)

**Comment by bopardikarsoham** [comment]
Sure @HuangJunye!

**Comment by Eric-Arellano** [comment]
This has been documented to explain how to build docs with tox.
