### ISSUE TITLE
Inconsistencies between contribution guidelines in README and PR template

### ISSUE THREAD

**Issue by Guillermo-Mijares-Vilarino** [Qiskit/qiskit-tutorials#1346]
### Informations

- **Qiskit version**: N/A
- **Python version**: N/A
- **Operating system**: N/A

### What is the current behavior?
The contribution guidelines from the [README](https://github.com/Qiskit/qiskit-tutorials#contribution-guidelines) are inconsistent with the [PR template](https://github.com/Qiskit/qiskit-tutorials/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1).

In particular, the PR template asks you to follow these steps:

> ✅ I have added the tests to cover my changes.
> ✅ I have updated the documentation accordingly.

However the README states that 

> In order for a tutorial to show up in the Qiskit documentation, after successful merging, an additional PR needs to be made in the [Qiskit meta-repo](https://github.com/Qiskit/qiskit) to trigger the rebuilding of the documentation.

So you are not expected to update the documentation until AFTER your PR got approved but for the PR to be approved in the first place you are expected to have already updated the documentation.

And there is no mention of tests in the README or the [contribution guidelines](https://github.com/Qiskit/qiskit-tutorials/blob/master/.github/CONTRIBUTING.md) to which the README links you. 

There isn't a test folder in the repo either. Which tests are we supposed to add?

### Steps to reproduce the problem

* Open [README](https://github.com/Qiskit/qiskit-tutorials#contribution-guidelines) and [PR template](https://github.com/Qiskit/qiskit-tutorials/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1) 
* Compare the parts mentioned above.

### What is the expected behavior?
Users can get confused when trying to do PRs so some of them may not upload valid and useful contributions to Qiskit.

### Suggested solutions
Update PR template to reflect the qiskit-tutorials guidelines.

**Comment by Eric-Arellano** [comment]
Thanks! This repo is being archived very soon so we can ignore this.
