### ISSUE TITLE
Function for printing data/dataframe for qiskit_finance data providers (YahooDataProvider, RandomDataProvider, ...)

### ISSUE THREAD

**Issue by VSGD** [Qiskit/qiskit-tutorials#1347]
### What is the expected behavior?

1. The function should be able to print the data/dataframe.
2. one function to convert data from yahoodataprovider (along with other data providers) to pandas so all other functions of pandas can be accessed.

**Comment by ElePT** [comment]
Hi thanks for your interest and apologies for the slow response! We are currently in the process of reorganising the Qiskit Tutorials, archiving this repo and moving the existing tutorials to the main qiskit repo or other appropriate projects. During this transition we will be focusing on maintaining/improving our existing content and are not able to take submissions for brand new tutorials at this time

In this case, the material mentioned in this issue already belonged to a different project: https://github.com/qiskit-community/qiskit-finance, I would suggest you to re-open this issue in qiskit-finance if you still find it relevant.
Thanks anyway for your feedback and helping us make Qiskit better! 🚀

**Comment by ElePT** [comment]
Hi thanks for your interest and apologies for the slow response! We are currently in the process of reorganising the Qiskit Tutorials, archiving this repo and moving the existing tutorials to the main qiskit repo or other appropriate projects. During this transition we will be focusing on maintaining/improving our existing content and are not able to take submissions for brand new tutorials at this time

In this case, the material mentioned in this issue already belonged to a different project: https://github.com/qiskit-community/qiskit-finance, I would suggest you to re-open this issue in qiskit-finance if you still find it relevant.
Thanks anyway for your feedback and helping us make Qiskit better! 🚀
