### ISSUE TITLE
Incorrect Notation  for two entangled qubits

### ISSUE THREAD

**Issue by purduequaic** [Qiskit/qiskit-tutorials#1359]
### Informations
In https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/simulators/1_aer_provider.ipynb
- **Qiskit version**: 0.25.0
- **Python version**: 3.7.7
- **Operating system**: Darwin

### What is the current behavior?
In https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/simulators/1_aer_provider.ipynb,  
Simulating a quantum circuit,
| Psi> = 1/2(|0, 0> + |1, 1>

### Steps to reproduce the problem
1. Replace 1/2 by 1/sqrt(2)  -- will be Math operator for sqrt
2. get rids of two commas.

### What is the expected behavior?
1/sqrt(2) instead 1/2
no commas.

### Suggested solutions
1. Replace 1/2 by 1/sqrt(2)  -- will be Math operator for sqrt
2. get rids of two commas.

**Comment by Raghav-Bell** [comment]
This issue has been resolved as per PR #1375. Please close this issue.
