### ISSUE TITLE
Add auto-linting tool from Qiskit Textbook to Qiskit Tutorials

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-tutorials#1393]
### What is the expected behavior?

@frankharkins has developed auto-linting tool for code and content for the Qiskit Textbook. We are planning to adapt the tool for this repo and add to CI tests for incoming PRs.

**Comment by frankharkins** [comment]
Thanks Junye, please assign me

**Comment by Eric-Arellano** [comment]
This will now be a decision for the qiksit terra repo, since this is being archived.
