### ISSUE TITLE
Enhance VQE-molecules tutorial to include primitives.

### ISSUE THREAD

**Issue by david-alber** [Qiskit/qiskit-tutorials#1394]
Enhance the coding examples in the [VQE-molecules](https://qiskit.org/textbook/ch-applications/vqe-molecules.html) tutorial with the usage of Qiskit primitives Estimator and Sampler and showcase the effect of error mitigation options.

**Comment by david-alber** [comment]
I would love to go ahead and start with the documentation enhancement myself. 
Since this would be my first contribution it would be great to get some feedback about my suggestions from more experienced members (@HuangJunye, @ElePT ) first :).

**Comment by woodsp-ibm** [comment]
I will note the runtime has this https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/vqe_with_estimator.html For textbook context it is held elsewhere so a contribution to that an issue here https://github.com/Qiskit/platypus would be more in context.

**Comment by david-alber** [comment]
@woodsp-ibm VQE-documentation enhancement is indeed an open issue in Qiskit/platypus. 
I will thus close the issue here.
