### ISSUE TITLE
Remove try/except in 07_grovers_algorithm

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-tutorials#1396]
The [Grover’s algorithm examples](https://qiskit.org/documentation/tutorials/algorithms/07_grover_examples.html) tutorial has some try/except blocks to catch missing libraries. For example:

```python
oracle = None
try:
    oracle = PhaseOracle.from_dimacs_file(file_name)
except MissingOptionalLibraryError as ex:
    print(ex)
```

I assume this is so the notebook runs for users with missing libraries. If so, I recommend letting the code raise an error, as the notebook doesn't produce any useful results if missing the libraries.

**Comment by Eric-Arellano** [comment]
This would mean that we can't build the docs on those platforms like macOS ARM because tweedledum cannot be installed there. Ideally we could error in certain environments and not others. 

In the meantime, our approach is to check our generated docs to make sure it worked properly.
