### ISSUE TITLE
Improve Quantum Approximate Optimization Algorithm tutorial if needed

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1406]
Part of Qiskit/qiskit-tutorials#1401

**Comment by divshacker** [comment]
This tutorial don't need any further improvement as the functions used in the tutorial are all updated and don't have any depreciation warnings. If there's any change that needs to be done, then please let me know. If there is nothing, then please close this issue. 
Thanks 
@woodsp-ibm @HuangJunye
