### ISSUE TITLE
Use our tutorial's checklist to improve our sample algorithms in qiskit tutorials

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1420]
Using our [tutorial guide](https://qiskit.github.io/qiskit_sphinx_theme/tutorials/index.html), make sure that our sample algorithms tutorials has the quality we want, and if not, improve them:

- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1421

**Comment by ElePT** [comment]
Given that this tutorial will no longer be maintained in its new location (in the context of the migration away from the metapackage), I think that we can close this issue.
