### ISSUE TITLE
Improve Iterative Quantum Phase Estimation Algorithm

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1421]
Part of Qiskit/qiskit-tutorials#1420 

It looks like [this tutorial](https://qiskit.org/documentation/tutorials/textbook/01_IQPE.html) is the same as [this other one](https://qiskit.org/documentation/tutorials/algorithms/09_IQPE.html), but they come form different files. Having duplicated content on different files makes maintenance harder, so we should decide which one we want to delete. Another option could be directly remove the "[Sample algorithms in qiskit](https://qiskit.org/documentation/tutorials.html#sample-algorithms-in-qiskit)" section

**Comment by woodsp-ibm** [comment]
The `algorithms` tutorials were tutorials around using the algorithms as supplied in Qiskit. This https://qiskit.org/documentation/tutorials/algorithms/09_IQPE.html seems to have been included at some point but for me would be more relevant as textbook and/or community content.

**Comment by ElePT** [comment]
Hi! As @woodsp-ibm mentioned in his comment, we consider that this material would be more relevant as textbook and/or community content. It does not use any of the algorithms supplied in `qiskit-algorithms`, but rather shows how to build the algorithm from scratch. For this reason, it has not been migrated to the new `qiskit-algorithms` tutorials section, and given the current context, I believe this issue can be closed.
