### ISSUE TITLE
Use our tutorial's checklist to improve our operators tutorials

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1422]
Using our [tutorial guide](https://qiskit.github.io/qiskit_sphinx_theme/tutorials/), make sure that our operators tutorials has the quality we want, and if not, improve them:

- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1423
- [ ] https://github.com/Qiskit/qiskit-tutorials/issues/1424

**Comment by javabster** [comment]
closing this as opflow is now deprecated
