### ISSUE TITLE
Improve Qiskit Gradient Framework tutorial if needed

### ISSUE THREAD

**Issue by y4izus** [Qiskit/qiskit-tutorials#1424]
Part of https://github.com/Qiskit/qiskit-tutorials/issues/1422

**Comment by woodsp-ibm** [comment]
I will note that `opflow` is planned to be deprecated in the upcoming 0.24.0 and will be removed in the future Qiskit/qiskit-terra#9176 as such these tutorials will no longer be relevant at that point.
