### ISSUE TITLE
Mathematical building blocks

### ISSUE THREAD

**Issue by InfamousPlatypus** [Qiskit/qiskit-tutorials#1439]
I recently realized there is not really any good tutorial on basic math (addition, subtraction etc.) for quantum computers. I see most if not all of the subjects needed in the textbook, but nothing explicitly stating how to do that. I would like to see (and can make) a page or two with addition, subtraction, multiplication, division, possibly powers and polynomials.

**Comment by javabster** [comment]
Hi thanks for your interest and apologies for the slow response! We are currently in the process of reorganising the Qiskit Tutorials, archiving this repo and moving the existing tutorials to the main qiskit repo or other appropriate projects. During this transition we will be focusing on maintaining/improving our existing content and are not able to take submissions for brand new tutorials at this time

Thanks anyway for your feedback and helping us make Qiskit better! 🚀
