### ISSUE TITLE
AttributeError: 'Estimator' object has no attribute 'draw'

### ISSUE THREAD

**Issue by sirgeorgesawcon** [Qiskit/qiskit-tutorials#1444]
### Informations

- **Qiskit version**: 0.23.3
- **Python version**:3.11.3
- **Operating system**:Windows 11

### What is the current behavior?

Following the qiskit tutorial exactly [Tutorial](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/algorithms/01_algorithms_introduction.ipynb) , I'm getting the error
`AttributeError: 'Estimator' object has no attribute 'draw'`

### Steps to reproduce the problem

Just follow the tutorial as it is, no change in any code blocks

### What is the expected behavior?

The code should run without any output.

### Suggested solutions
 The `vqe.py` file asks for 
`if self.ansatz is not None:
--> ret += "{}".format(self.ansatz.draw(output="text"))`
 this `draw` is somehow not attributed in the Estimator class.
![issue](https://user-images.githubusercontent.com/63145298/233893839-e842ac71-0db3-48c4-b4c6-5125f0a1919c.png)

**Comment by woodsp-ibm** [comment]
The tutorial has this below to import VQE (this is the new Estimator based VQE)

> from qiskit.algorithms.minimum_eigensolvers import VQE

your code above is

> from qiskit.algorithms.minimum_eigen_solvers import VQE

which is importing an older VQE from `minimum_eigen_solvers` (which is being deprecated in the upcomnig release) where there is an `_` in `eigen_solvers` which the newly located VQE does not have. If you correct the import, so it matches the tutorial, then it will work.

**Comment by woodsp-ibm** [comment]
I will go ahead and close this in the absence of any feedback. The above should have solved your issue, in that you need to use the same VQE as the tutorial uses - there is the older legacy one, which I imagine you accidentally used, and the newer primitive based one that uses an Estimator.
