### ISSUE TITLE
Broken thumbnail for Grover tutorial

### ISSUE THREAD

**Issue by wshanks** [Qiskit/qiskit-tutorials#1450]
### What is the current behavior?

On https://qiskit.org/documentation/tutorials.html, I see this:

![image](https://user-images.githubusercontent.com/1178780/236500652-023b3fc3-ec1f-491c-abef-5d4397e3fa99.png)

### What is the expected behavior?

It should show the default qiskit logo instead of "BROKEN THUMB NAIL"

**Comment by coruscating** [comment]
This can be fixed by adding [this code snippet](https://github.com/Qiskit/qiskit-metapackage/issues/1707#issuecomment-1487202520) to `conf.py`.

**Comment by Raghav-Bell** [comment]
I think this is resolved now, please close this issue.

**Comment by Eric-Arellano** [comment]
Thanks, @Raghav-Bell!
