### ISSUE TITLE
Refer to Trotter Evolution in the video "Time Evolution with Qiskit Nature & Opflow"

### ISSUE THREAD

**Issue by OuCheng-Fu** [Qiskit/qiskit-tutorials#1452]
Dear Everyone,

     I asked about how to implement Quantum Imaginary Time Evolution on IBM Qiskit, and I tried to implement Trotter Time Evolution by referencing this video ([Time Evolution with Qiskit Nature & Opflow - YouTube](https://www.youtube.com/watch?v=PY6PWondOeQ&list=LL&index=1)). At 7:23 of this video, the author tries to implement the trotter evolution of Ising model by the codes in the first picture; however, when I try to implement it on qiskit, it raises two errors: one is for time range: int object is not iterable and another one is "name 'param_bind' is not defined", like the latter 2 pictures I attached. What may be wrong in this process?

                                                                       Sincerely,

                                                                       Ou, Cheng-Fu

                                                                       2023/5/13

![Trotter Evolution Code](https://github.com/Qiskit/qiskit-tutorials/assets/133572432/88a53b1d-b723-4e58-b902-3596cf32fc24)
![Error 1](https://github.com/Qiskit/qiskit-tutorials/assets/133572432/f7631b45-a86a-401b-857f-9526fbe239ee)
![Error 2](https://github.com/Qiskit/qiskit-tutorials/assets/133572432/c73d9948-3acb-46c9-a7a2-d0551174027a)

**Comment by Raghav-Bell** [comment]
As per documentation `bind_parameters({parameter: parameter_value})` bind_parameters takes dictionary as input.Here param_bind refers to dictionary. ref: [Qiskit documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.bind_parameters.html#qiskit.circuit.QuantumCircuit.bind_parameters) . I will share more details on this issue shortly as of now initialize param_bind  as `param_bind=dict()` .

**Comment by OuCheng-Fu** [comment]
Thank you. I have checked it and solved this issue.
