### ISSUE TITLE
Refer to the problem of the tutorial "Max-Cut and Traveling Salesman Problem"

### ISSUE THREAD

**Issue by OuCheng-Fu** [Qiskit/qiskit-tutorials#1453]
To whom it may concern,

     I am Ou, Cheng-Fu. I am a graduate student of Physics in National Taiwan University. I am trying to implement the Quadratic Program of Traveling Salesman Problem mentioned in IBM Qiskit Page [Max-Cut and Traveling Salesman Problem — Qiskit Optimization 0.5.0 documentation](https://qiskit.org/ecosystem/optimization/tutorials/06_examples_max_cut_and_tsp.html). In the tutorial, to implement the Traveling Salesman Problem using the Qiskit Optimization Tsp module, the code is about creating a graph of random instance with random adjacent matrix and turn it into the quadratic program and Ising model QUBO problem. However, I don't want a random instance, I want to specify a specific adjacent matrix and turn it into a QUBO formula. When I try to implement it by specifying such a matrix (appearing like the picture I attached) it gives our an error as " 'Graph' object has no attribute 'to_quadratic_program' ". I have checked the version of qiskit terra and qiskit optimization, it fits the tutorial. How can I solve this problem?

                                                               Sincerely,

                                                               Ou, Cheng-Fu

                                                               2023/5/14
![Error for Tsp qudratic program](https://github.com/Qiskit/qiskit-tutorials/assets/133572432/6a70cc01-fa15-49a0-963c-84c783cd8721)

**Comment by v2rinku** [comment]
Hello Ou, Cheng-Fu, can you please assign this issue to me, thanks

**Comment by OuCheng-Fu** [comment]
There is no "assign" settings on my issue page, so I can't assign you because I am not the owner or the collaborator of the repository. If you want to answer this issue, answer directly by reply.

**Comment by OuCheng-Fu** [comment]
Thank you. I changed the codes associating to the variable "tsp" to the source code of "to_quadratic_program" and build a model from it so the problem is solved.
