### ISSUE TITLE
Algorithms tutorials 02_, 03_ and 04_ need amending to not use deprecated code.

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-tutorials#1456]
Three tutorials 02_..., 03_... and 04_... all still use a PauliSumOp. Since the H2_op started out as a SparsePauliOp I am not sure why its later converted to a PauliSumOp. In the case of 03 that may be as it still is using the deprecated NumPyMinimumEigensolver. These uses lead to deprecated messages in the tutorials so they need to be updated accordingly.

**Comment by TannerTorrey3** [comment]
Im trying to get some contributions for the Qiskit advocate application. I found the issues you're discussing let me know if I should go ahead and fix them.

**Comment by TannerTorrey3** [comment]
All three tutorials use NumPyMinimumEigensolver and make the swap to PauliSumOp.

**Comment by woodsp-ibm** [comment]
@TannerTorrey3 

* #1467 above has already fixed the use of deprecated code there for 03_....
* #1446 is by same author for 02_.... and I am expecting it to be corrected there likewise

The 04_.... VQD tutorial I don't believe is being addressed so if you'd like to do that one it would be good.

**Comment by divshacker** [comment]
Yes, I looked over the 4th tutorial and that just needs this paulisumop fix so I didn't made a separate PR for this much small Change. I was planning to cover it up in other PRs. But as you (@TannerTorrey3) wanted to contribute for Qiskit Advocate application then go ahead 🙂 as application just opened. 
BTW I am doing a QAMP project improving all of the tutorials (If needed) of this Qiskit tutorial repo.

**Comment by TannerTorrey3** [comment]
@divshacker Ok thank you I'll get on those fixes. Let me know if I can be of assistance with QAMP. I definitely have some knowledge gaps with QC,  but should be able to be some assistance.

**Comment by Eric-Arellano** [comment]
This is being handled as part of https://github.com/qiskit-community/qiskit-algorithms/pull/44.
