### ISSUE TITLE
For the problem in Qiskit Youtube Video "Time Evolution with Qiskit Nature & Opflow"

### ISSUE THREAD

**Issue by OuCheng-Fu** [Qiskit/qiskit-tutorials#1457]
Dear Everyone,
     I tried to implement Trotter Time Evolution by referencing this video ([Time Evolution with Qiskit Nature & Opflow - YouTube](https://www.youtube.com/watch?v=PY6PWondOeQ&list=LL&index=1)). Thanks for someone providing me some information, I try to implement this method to do Quantum Imaginary Time Evolution as in this issue #1452, and I got 'name 'param_bind' is not defined'. I tried to import more modules such as qiskit Parameters, and the problem is not solved. I also tried other possibilities, which is in the attached pictures, they give out similar or same errors. What exactly is 'param_bind'? Is it a module or a class in Python?
![Error 3](https://github.com/Qiskit/qiskit-tutorials/assets/133572432/02123b79-1539-42cf-993f-d2182719bc28)
![Error 4](https://github.com/Qiskit/qiskit-tutorials/assets/133572432/5b535bd8-b14f-49bb-82c9-f3334dbfbd1e)
![Error 5](https://github.com/Qiskit/qiskit-tutorials/assets/133572432/0fd91a96-52e5-44aa-893b-598c3a043813)

**Comment by Raghav-Bell** [comment]
Hey! @OuCheng-Fu  please do not repeat the issue. I have answered your query in PR #1452 ,if you want more help in that you can use [slack](https://qisk.it/join-slack).

**Comment by OuCheng-Fu** [comment]
> Hey! @OuCheng-Fu please do not repeat the issue. I have answered your query in PR #1452 ,if you want more help in that you can use [slack](https://qisk.it/join-slack).

Thank you for reply. I would close this issue.
