### ISSUE TITLE
HHL algorithm section

### ISSUE THREAD

**Issue by Chamxgus** [Qiskit/qiskit-tutorials#1458]
Steps 2 and 5 in section 2B are not properly integrated with MathJax and LaTeX and display incorrectly. Most likely a simple typo.

**Comment by ElePT** [comment]
Hi, thanks for your interest and apologies for the slow response. This tutorial was removed from our codebase and replaced with educational content [in our textbook](https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation), which as far as I can see, does not contain the same bug, so I will go ahead and close this issue.

Thanks anyway for your feedback and helping us make Qiskit better! 🚀
