### ISSUE TITLE
Tutorial on using Qiskit's qiskit.algorithms.time_evolvers.variational package for variational quantum imaginary and real-time evolution based on McLachlan's variational principle

### ISSUE THREAD

**Issue by ptwnimbe1** [Qiskit/qiskit-tutorials#1462]
Variational Quantum Time Evolution:

1.Variational quantum time evolution leverages variational principles to approximate the time evolution of quantum systems. It aims to find the optimal parameters that minimize the discrepancy between the simulated time evolution and the desired target evolution.

2. Import Required Libraries

3. Define the Hamiltonian:
Specify the Hamiltonian of the quantum system you want to simulate. You can represent it using the SparsePauliOp from Qiskit's quantum_info module.

4. Initialize the Ansatz:
Create an ansatz, which is a parameterized quantum circuit, using Qiskit's circuit library.

5. Set Initial Parameter Values:
Initialize the parameter values of the ansatz. These values will be iteratively updated during the optimization process.

6. Define the Variational Principle:
Specify the variational principle to be used. For variational quantum time evolution, you can use ImaginaryMcLachlanPrinciple from Qiskit's qiskit.algorithms.time_evolvers.variational module. 

7. Define the Time Evolution Problem:
Create a TimeEvolutionProblem object by specifying the Hamiltonian and the desired evolution time. 

8. Run Variational Quantum Time Evolution:
Create a VarQITE object with the ansatz, variational principle, and initial parameter values. Then, call the evolve method with the time evolution problem. 

By following these steps, you can leverage Qiskit's qiskit.algorithms.time_evolvers.variational package to perform variational quantum imaginary and real-time evolution based on McLachlan's variational principle.

**Comment by woodsp-ibm** [comment]
Related  to #1391

**Comment by javabster** [comment]
Hi thanks for your interest and apologies for the slow response! We are currently in the process of reorganising the Qiskit Tutorials, archiving this repo and moving the existing tutorials to the main qiskit repo or other appropriate projects. During this transition we will be focusing on maintaining/improving our existing content and are not able to take submissions for brand new tutorials at this time

Thanks anyway for your feedback and helping us make Qiskit better! 🚀
