### ISSUE TITLE
create a tutorial to demonstrate different entangled states

### ISSUE THREAD

**Issue by vishwanaveen** [Qiskit/qiskit-tutorials#1482]
states like ghz states ,Spin-squeezed cat states etc

**Comment by priyansh-1902** [comment]
Hi, I would like to work on this. Do you think this is a good first issue for me to work on?

**Comment by javabster** [comment]
Hi thanks for your interest and apologies for the slow response! We are currently in the process of reorganising the Qiskit Tutorials, archiving this repo and moving the existing tutorials to the main qiskit repo or other appropriate projects. During this transition we will be focusing on maintaining/improving our existing content and are not able to take submissions for brand new tutorials at this time

Thanks anyway for your feedback and helping us make Qiskit better! 🚀
