### ISSUE TITLE
qiskit - aqua

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-tutorials#290]
## Description

In the folder qiskit/aqua can we get the developer notebooks. @chunfuchen this is basically you pr #280 can you change in this the using qconfig to IBMQ.load_accounts()

- [x] Chemistry
- [x] Optimization
- [x] Artificial Intelligence
- [x] finance

## Your Environment

* QISKit version:
* Python version:

**Comment by chunfuchen** [comment]
updated PR #280 for the issue.

**Comment by chunfuchen** [comment]
related to #348  and #351

**Comment by jaygambetta** [comment]
closing as notebooks are updated to 0.7
