### ISSUE TITLE
[Not urgent] Completing the community standards?

### ISSUE THREAD

**Issue by rraymondhp** [Qiskit/qiskit-tutorials#326]
## Description

The link below alerts that qiskit-tutorial is still behind the standard of github repository (templates etc.). Do we need to handle it explicitly (like qiskit-terra), or leave it behind as we have already fulfill them? 
https://github.com/Qiskit/qiskit-tutorial/community

## Your Environment

* QISKit version: v0.6
* Python version: 3.6

**Comment by jaygambetta** [comment]
Sure make a pr

**Comment by jaygambetta** [comment]
@rraymondhp is there any update.

**Comment by rraymondhp** [comment]
@jaygambetta  I am working on it. There are two ways:
1. The easiest by web tool at github. But it creates temporary new branches that can be deleted once merged.
2. Creating PRs. No new branches but quite complicated. 
Can I do 1?

**Comment by jaygambetta** [comment]
Sure do one.
