### ISSUE TITLE
Attempt to update Wigner Functions notebook

### ISSUE THREAD

**Issue by muneerqu** [Qiskit/qiskit-tutorials#339]
## Description

Following #337 I updated "wigner_functions.ipynb" to run on Qiskit 0.6.1 and I faced the following issues:

1. Couldn't use plot methods `plaquette` & `curve` in `plot_state()`
2. Couldn't adjust the `resolution` of the plots, no `res` parameter to pass in `plot_state()`

As a temporary solution, I added `plot_wigner_plaquette()` and `plot_wigner_curve()` methods from `terra` `(_state_visualization.py)` to the notebook to perform these plots.

Let me know if this is a possible/temporary solution to update the notebook.

## Your Environment

* QISKit version: 0.6.1
* Python version: 3.7

**Comment by jaygambetta** [comment]
yes, this is broken and plot_wigner_blah should not be used directly. @mtreinish these methods need to be options in plot_state. Maybe they are but I can't check now. I will look later when not traveling.

**Comment by jaygambetta** [comment]
moving to https://github.com/Qiskit/qiskit-terra/issues/1106 in terra.

**Comment by jaygambetta** [comment]
closing with #532
