### ISSUE TITLE
Imports for packages are not intsructive

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-tutorials#420]
## Description
Many tutorials start with a big block of imports. I don't this is optimal, since

* When tools are used later, it is not clear whether they are qiskit or not.

* Changes are made to notebooks making certain imports unnecessary, but they still remain (and provide problems for new versions). For example, the import of `CompositeGate` in [this notebook](https://github.com/Qiskit/qiskit-tutorial/blob/master/community/hello_world/string_comparison.ipynb), which is not used.

### Suggested solutions

Importing tools close to their first use, so that the context is clear. It should also be clear to remove them if the code is changed.

**Comment by quantumjim** [comment]
@attp @rraymondhp What do you think of adopting this style going forward?

**Comment by rraymondhp** [comment]
Thanks for pointing this. I agree we have to clean the import and start reviewing if they are needed at all.

**Comment by jaygambetta** [comment]
Show me the import block you are thinking.

**Comment by quantumjim** [comment]
Below is what I'm thinkingm using the sniopet from the qiskit website. Just a matter of importing directly before first use. Not best practice for actual usage, perhaps, but I think it better shows what needs to be imported and why.

```
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.cx(q[0], q[1])
qc.measure(q, c)

from qiskit import Aer
backend = Aer.get_backend('qasm_simulator')

from qiskit import execute
job_sim = execute(qc, backend)

sim_result = job_sim.result()

print(sim_result.get_counts(qc))
```

**Comment by attp** [comment]
I think we definitely need to check if tutorials are using what they import. However, I'm not sure about importing packages right before they are used. In my own code, I sometimes use the following convention so that the namespace of the functions I'm using is obvious:
```
import qiskit as qk

q = qk.QuantumRegister(2)
c = qk.ClassicalRegister(2)
qc = qk.QuantumCircuit(q, c)
```
