### ISSUE TITLE
Personal notes still to be found in Summary of Quantum Operations tutorial

### ISSUE THREAD

**Issue by attp** [Qiskit/qiskit-tutorials#436]
Personal notes found:

> I THINK SHOULD BE CALLED CPHASE(λ)

> NOTE I NEED TO FIX THIS AND DECIDE ON CONVENTION - I ACTUALLY THINK WE WANT A FOUR PARAMETER GATE AND JUST CALL IT CU AND TO REMOVE THIS GATE.

These should be resolved and removed.

**Comment by jaygambetta** [comment]
yeah, we can remove them.
