### ISSUE TITLE
Import error in QISKit 0.7.0

### ISSUE THREAD

**Issue by Tomev** [Qiskit/qiskit-tutorials#464]
## Description

Hello,

 I've updated QISKit to v. 0.7.0 but now, when I try to import circuits and registers via 

`from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister`

I'm geting an import error

> from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
> ImportError: cannot import name 'QuantumCircuit' from 'qiskit' (unknown location)

which occurrs in my PyCharm and in Anaconda Prompt. I tried changing import from above to

`from qiskit.circuit import QuantumCircuit, ClassicalRegister, QuantumRegister`

and the error changed to

> from qiskit.qasm import _qasm
> ImportError: cannot import name '_qasm' from 'qiskit.qasm' (unknown location),

but it still doesn't work. QISKit reinstallation didn't help.

What should I do or what am I doing wrong?

## Your Environment

* QISKit version: 0.7.0
* Python version: 3.7

**Comment by rraymondhp** [comment]
Hi, I had the same problem and to solve it I have to uninstall qiskit first and then reinstall (instead of upgrading). It is not due to qiskit-tutorial. Would you mind trying it first? 

I will post the issue to qiskit-terra too.

**Comment by Tomev** [comment]
Hi Ray,

it seems to have done the trick. Thanks.

**Comment by pifparfait** [comment]
Hi @rraymondhp and @Tomev 
I have the same problem... which version do you have now?
I have python 3.7.1 and Qiskit: 0.7

ImportError: cannot import name 'IBMQ' from 'qiskit' (/Users/parfait/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/qiskit/__init__.py)

Many thanks

**Comment by gplynch619** [comment]
Hi,

I am having the same problem. I tried uninstalling and reinstalling qiskit, but it has not worked. I previously had it working but after some updates I am getting:

`ImportError: cannot import name 'QuantumCircuit' form 'qiskit' (unknown location)`

I am using Python 3.7.2 and qiskit 0.7.0.
