### ISSUE TITLE
Python quit unexpectedly maxcut_and_tsp.ipynb

### ISSUE THREAD

**Issue by pifparfait** [Qiskit/qiskit-tutorials#485]
### Informations
qiskit/aqua/optimization/maxcut_and_tsp.ipynb

- **Qiskit version**: 0.7.0
- **Python version**: 3.7.2
- **Operating system**: Mac OS X 10.14.1 (18B75)

### What is the current behavior?
System Integrity Protection: enabled
Crashed Thread:        11
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

OMP: Error #15: Initializing libomp.a, but found libomp.a already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/

### Steps to reproduce the problem
Executing this part of algorithm
# run quantum algorithm with shots
seed = 10598

spsa = SPSA(max_trials=300)
ry = RY(qubitOp.num_qubits, depth=5, entanglement='linear')
vqe = VQE(qubitOp, ry, spsa, 'grouped_paulis')

backend = Aer.get_backend('qasm_simulator')
quantum_instance = QuantumInstance(backend=backend, shots=1024, seed=seed, seed_mapper=seed)

result = vqe.run(quantum_instance)

"""declarative approach, update the param from the previous cell.
params['algorithm']['operator_mode'] = 'grouped_paulis'
params['backend']['name'] = 'qasm_simulator'
params['backend']['shots'] = 1024
result = run_algorithm(params, algo_input)
"""

x = maxcut.sample_most_likely(result['eigvecs'][0])
print('energy:', result['energy'])
print('time:', result['eval_time'])
print('maxcut objective:', result['energy'] + offset)
print('solution:', maxcut.get_graph_solution(x))
print('solution objective:', maxcut.maxcut_value(x, w))
plot_histogram(result['eigvecs'][0])

colors = ['r' if maxcut.get_graph_solution(x)[i] == 0 else 'b' for i in range(n)]
nx.draw_networkx(G, node_color=colors, node_size=600, alpha = .8, pos=pos)

### What is the expected behavior?
NO error

### Suggested solutions
from qiskit import BasicAer instead of from qiskit import Aer

**Comment by jaygambetta** [comment]
Hi, @pifparfait thanks for the issue. It is the same as the one I made in https://github.com/Qiskit/qiskit-aer/issues/1. Since this is an Aer issue I'm going to close it here but link it to your issue for tracking purposes.

**Comment by pifparfait** [comment]
Hi, @jaygambetta I've got it! Thanks
