### ISSUE TITLE
quantum circuit drawing probelm

### ISSUE THREAD

**Issue by yangjy0826** [Qiskit/qiskit-tutorials#499]
Hi, 

I have just updated the qiskit to version 0.7. When I try drawing the quantum circuit using function `draw()` in `QuantumCircuit`, I find my result like this:
<img width="193" alt="qiskit_drawcircuit" src="https://user-images.githubusercontent.com/39376681/51250661-5d71b580-1997-11e9-9875-632bb397f5df.PNG">
which is very messy.

How can I solve this problem?

Thank you!

**Comment by yangjy0826** [comment]
Hi, thank you for your reply!
The output then shows ¨<Figure size 919.722x1028.42 with 1 Axes>¨, but I can't see the picture.

**Comment by rraymondhp** [comment]
How about having this at the first line of the cell:
```
%matplotlib inline
```

**Comment by yangjy0826** [comment]
Then it works. Thank you so much for the help.
