### ISSUE TITLE
pip install qiskit says invalid syantax

### ISSUE THREAD

**Issue by dharma111** [Qiskit/qiskit-tutorials#507]
### Informations

 **Qiskit version**:- 0.7.2
**Python version**:3.7
- **Operating system**:windows 10

### What is the current behavior?
when I type pip install qiskit
it says " invalid syntax "
![error](https://user-images.githubusercontent.com/22235030/51858838-acd2c100-235b-11e9-9613-ca8122423092.PNG)

**Comment by nonhermitian** [comment]
This is what happens when you try to run `pip install qiskit` inside of the Python terminal.  You need to be on the Windows command line to run `pip`

**Comment by jaygambetta** [comment]
closing as @nonhermitian is correct. If you still have questions please reopen.
