### ISSUE TITLE
Import error(Qconfig)

### ISSUE THREAD

**Issue by shashanka300** [Qiskit/qiskit-tutorials#519]
No module named 'Qconfig_IBMQ_experience'
No module named 'Qconfig_IBMQ_network'

- **Qiskit version**: 0.7.2
- **Python version**:3.6.4
- **Operating system**: windows 10
### Steps to reproduce the problem

import Qconfig_IBMQ_experience
import Qconfig_IBMQ_network

**Comment by jaygambetta** [comment]
These are files you need to make yourself as they contain your user information. @attp can you think about how we can make this clearer in the documentation in this notebook.

**Comment by rraymondhp** [comment]
Hi, 

I think you write a wrong `import` or the files `Qconfig_IBMQ_*` are not at the same directory as the file you have. 

For the latter case, please place the files `Qconfig_IBMQ_experience` at the same directory as your notebook/program file. 

And, with IBMQ module, you do not need to import `Qconfig` files anymore. For the new way of using account, please refer to the tutorial below:

https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/jupyter/jupyter_backend_tools.ipynb

**Comment by rraymondhp** [comment]
Here is the more detailed tutorial that shows how to use the IBMQ credentials: 

https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/basics/the_ibmq_provider.ipynb

I am closing this issue, but feel free to reopen it if you still encounter similar problems.
