### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by jrontynen** [Qiskit/qiskit-tutorials#526]
I try to follow the installation instructions for the qiskit tutorials on Ubuntu 18.04, but I get the error below when building the environment. I think this is the reason I cannot import qiskit in a jupyter-notebook but get the following error instead: 

> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-2-3453bc9fe867> in <module>()
>       1 import numpy as np
> ----> 2 from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
>       3 from qiskit import execute
> ModuleNotFoundError: No module named 'qiskit'

Here is what I get when trying to build the environment:

> joel@joel-XPS:~/jupyter/qiskit/qiskit-tutorials-0.7.0$ conda env update -f environment.yml
> Collecting package metadata: done
> Solving environment: done
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> ++ /home/joel/anaconda3/bin/conda shell.posix hook
> + eval 'export CONDA_EXE="/home/joel/anaconda3/bin/conda"
> # Copyright (C) 2012 Anaconda, Inc
> # SPDX-License-Identifier: BSD-3-Clause
> 
> __conda_hashr() {
>     if [ -n "${ZSH_VERSION:+x}" ]; then
>         \rehash
>     elif [ -n "${POSH_VERSION:+x}" ]; then
>         :  # pass
>     else
>         \hash -r
>     fi
> }
> 
> __conda_activate() {
>     if [ -n "${CONDA_PS1_BACKUP:+x}" ]; then
>         # Handle transition from shell activated with conda <= 4.3 to a subsequent activation
>         # after conda updated to >= 4.4. See issue #6173.
>         PS1="$CONDA_PS1_BACKUP"
>         \unset CONDA_PS1_BACKUP
>     fi
> 
>     \local cmd="$1"
>     shift
>     \local ask_conda
>     ask_conda="$(PS1="$PS1" "$CONDA_EXE" shell.posix "$cmd" "$@")" || \return $?
>     \eval "$ask_conda"
>     __conda_hashr
> }
> 
> __conda_reactivate() {
>     \local ask_conda
>     ask_conda="$(PS1="$PS1" "$CONDA_EXE" shell.posix reactivate)" || \return $?
>     \eval "$ask_conda"
>     __conda_hashr
> }
> 
> conda() {
>     if [ "$#" -lt 1 ]; then
>         "$CONDA_EXE"
>     else
>         \local cmd="$1"
>         shift
>         case "$cmd" in
>             activate|deactivate)
>                 __conda_activate "$cmd" "$@"
>                 ;;
>             install|update|upgrade|remove|uninstall)
>                 "$CONDA_EXE" "$cmd" "$@" && __conda_reactivate
>                 ;;
>             *) "$CONDA_EXE" "$cmd" "$@" ;;
>         esac
>     fi
> }
> 
> if [ -z "${CONDA_SHLVL+x}" ]; then
>     \export CONDA_SHLVL=0
>     PATH="$(dirname "$(dirname "$CONDA_EXE")")/condabin:${PATH:-}"
>     \export PATH
> 
>     # We'\''re not allowing PS1 to be unbound. It must at least be set.
>     # However, we'\''re not exporting it, which can cause problems when starting a second shell
>     # via a first shell (i.e. starting zsh from bash).
>     if [ -z "${PS1+x}" ]; then
>         PS1=
>     fi
> fi
> 
> 
> conda activate base'
> ++ export CONDA_EXE=/home/joel/anaconda3/bin/conda
> ++ CONDA_EXE=/home/joel/anaconda3/bin/conda
> ++ '[' -z '' ']'
> ++ export CONDA_SHLVL=0
> ++ CONDA_SHLVL=0
> ++++ dirname /home/joel/anaconda3/bin/conda
> +++ dirname /home/joel/anaconda3/bin
> ++ PATH=/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> ++ export PATH
> ++ '[' -z '' ']'
> ++ PS1=
> ++ conda activate base
> ++ '[' 2 -lt 1 ']'
> ++ local cmd=activate
> ++ shift
> ++ case "$cmd" in
> ++ __conda_activate activate base
> ++ '[' -n '' ']'
> ++ local cmd=activate
> ++ shift
> ++ local ask_conda
> +++ PS1=
> +++ /home/joel/anaconda3/bin/conda shell.posix activate base
> ++ ask_conda='PS1='\''(base) '\''
> \export CONDA_DEFAULT_ENV='\''base'\''
> \export CONDA_EXE='\''/home/joel/anaconda3/bin/conda'\''
> \export CONDA_PREFIX='\''/home/joel/anaconda3'\''
> \export CONDA_PROMPT_MODIFIER='\''(base) '\''
> \export CONDA_PYTHON_EXE='\''/home/joel/anaconda3/bin/python'\''
> \export CONDA_SHLVL='\''1'\''
> \export PATH='\''/home/joel/anaconda3/bin:/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'\'''
> ++ eval 'PS1='\''(base) '\''
> \export CONDA_DEFAULT_ENV='\''base'\''
> \export CONDA_EXE='\''/home/joel/anaconda3/bin/conda'\''
> \export CONDA_PREFIX='\''/home/joel/anaconda3'\''
> \export CONDA_PROMPT_MODIFIER='\''(base) '\''
> \export CONDA_PYTHON_EXE='\''/home/joel/anaconda3/bin/python'\''
> \export CONDA_SHLVL='\''1'\''
> \export PATH='\''/home/joel/anaconda3/bin:/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'\'''
> +++ PS1='(base) '
> +++ export CONDA_DEFAULT_ENV=base
> +++ CONDA_DEFAULT_ENV=base
> +++ export CONDA_EXE=/home/joel/anaconda3/bin/conda
> +++ CONDA_EXE=/home/joel/anaconda3/bin/conda
> +++ export CONDA_PREFIX=/home/joel/anaconda3
> +++ CONDA_PREFIX=/home/joel/anaconda3
> +++ export 'CONDA_PROMPT_MODIFIER=(base) '
> +++ CONDA_PROMPT_MODIFIER='(base) '
> +++ export CONDA_PYTHON_EXE=/home/joel/anaconda3/bin/python
> +++ CONDA_PYTHON_EXE=/home/joel/anaconda3/bin/python
> +++ export CONDA_SHLVL=1
> +++ CONDA_SHLVL=1
> +++ export PATH=/home/joel/anaconda3/bin:/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> +++ PATH=/home/joel/anaconda3/bin:/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> ++ __conda_hashr
> ++ '[' -n '' ']'
> ++ '[' -n '' ']'
> ++ hash -r
> + conda activate /home/joel/anaconda3/envs/Qiskitenv
> + '[' 2 -lt 1 ']'
> + local cmd=activate
> + shift
> + case "$cmd" in
> + __conda_activate activate /home/joel/anaconda3/envs/Qiskitenv
> + '[' -n '' ']'
> + local cmd=activate
> + shift
> + local ask_conda
> ++ PS1='(base) '
> ++ /home/joel/anaconda3/bin/conda shell.posix activate /home/joel/anaconda3/envs/Qiskitenv
> + ask_conda='PS1='\''(Qiskitenv) '\''
> \export CONDA_DEFAULT_ENV='\''Qiskitenv'\''
> \export CONDA_PREFIX='\''/home/joel/anaconda3/envs/Qiskitenv'\''
> \export CONDA_PREFIX_1='\''/home/joel/anaconda3'\''
> \export CONDA_PROMPT_MODIFIER='\''(Qiskitenv) '\''
> \export CONDA_SHLVL='\''2'\''
> \export PATH='\''/home/joel/anaconda3/envs/Qiskitenv/bin:/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'\'''
> + eval 'PS1='\''(Qiskitenv) '\''
> \export CONDA_DEFAULT_ENV='\''Qiskitenv'\''
> \export CONDA_PREFIX='\''/home/joel/anaconda3/envs/Qiskitenv'\''
> \export CONDA_PREFIX_1='\''/home/joel/anaconda3'\''
> \export CONDA_PROMPT_MODIFIER='\''(Qiskitenv) '\''
> \export CONDA_SHLVL='\''2'\''
> \export PATH='\''/home/joel/anaconda3/envs/Qiskitenv/bin:/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'\'''
> ++ PS1='(Qiskitenv) '
> ++ export CONDA_DEFAULT_ENV=Qiskitenv
> ++ CONDA_DEFAULT_ENV=Qiskitenv
> ++ export CONDA_PREFIX=/home/joel/anaconda3/envs/Qiskitenv
> ++ CONDA_PREFIX=/home/joel/anaconda3/envs/Qiskitenv
> ++ export CONDA_PREFIX_1=/home/joel/anaconda3
> ++ CONDA_PREFIX_1=/home/joel/anaconda3
> ++ export 'CONDA_PROMPT_MODIFIER=(Qiskitenv) '
> ++ CONDA_PROMPT_MODIFIER='(Qiskitenv) '
> ++ export CONDA_SHLVL=2
> ++ CONDA_SHLVL=2
> ++ export PATH=/home/joel/anaconda3/envs/Qiskitenv/bin:/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> ++ PATH=/home/joel/anaconda3/envs/Qiskitenv/bin:/home/joel/anaconda3/condabin:/home/joel/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> + __conda_hashr
> + '[' -n '' ']'
> + '[' -n '' ']'
> + hash -r
> + /home/joel/anaconda3/envs/Qiskitenv/bin/python /home/joel/anaconda3/envs/Qiskitenv/bin/pip --disable-pip-version-check install -r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt
> Collecting qiskit (from -r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/7a/4a/bc00cc835794bb5247146d895586284759fe8e726648cfbb2f977e484bec/qiskit-0.7.2.tar.gz
> Collecting qiskit-aqua (from -r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/52/55/14810048c9e2eecd7949b1868e9871ecba0dd680d9688172994773c6696f/qiskit_aqua-0.4.1-py3-none-any.whl
> Collecting qiskit-chemistry (from -r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 3))
>   Using cached https://files.pythonhosted.org/packages/47/09/1b929005bdc7ae8d8b8986c1b56770663a1b1d00349b14a85e73b4c66ac1/qiskit_chemistry-0.4.2-py3-none-any.whl
> Collecting qiskit-terra<0.8,>=0.7 (from qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/04/09/84508da42db2ded1ef3f8b68577f6e18aee4a35905d4830c2b7251fa6173/qiskit_terra-0.7.0-cp37-cp37m-manylinux1_x86_64.whl
> Collecting qiskit-aer<0.2,>=0.1 (from qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/6a/bd/3d615fbbd906da3e2f63c3fe2a161ee13393bc74487854797c8a21dd9f0e/qiskit_aer-0.1.1-cp37-cp37m-manylinux1_x86_64.whl
> Collecting sympy>=1.3 (from qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/dd/f6/ed485ff22efdd7b371d0dbbf6d77ad61c3b3b7e0815a83c89cbb38ce35de/sympy-1.3.tar.gz
> Requirement already satisfied: numpy>=1.13 in /home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages (from qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2)) (1.15.4)
> Collecting scipy!=0.19.1,>=0.19 (from qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/3e/7e/5cee36eee5b3194687232f6150a89a38f784883c612db7f4da2ab190980d/scipy-1.2.1-cp37-cp37m-manylinux1_x86_64.whl
> Collecting psutil>=5 (from qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/c7/01/7c30b247cdc5ba29623faa5c8cf1f1bbf7e041783c340414b0ed7e067c64/psutil-5.5.1.tar.gz
> Requirement already satisfied: setuptools>=40.5.0 in /home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages (from qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2)) (40.8.0)
> Collecting jsonschema<2.7,>=2.6 (from qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
> Collecting scikit-learn==0.20.0 (from qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/56/7d/0737aed3e157fb90a1eaecb1cbfa5742fa4206fb305c8f157b666b71da14/scikit_learn-0.20.0-cp37-cp37m-manylinux1_x86_64.whl
> Collecting cvxopt (from qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/9b/84/e8c883bbfc972dc9f7b2ca9f97c56d73a44a7dfa700f73746ae0d2569cb0/cvxopt-1.2.3-cp37-cp37m-manylinux1_x86_64.whl
> Collecting h5py (from qiskit-chemistry->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 3))
>   Using cached https://files.pythonhosted.org/packages/8e/fd/2ca5c4f4ed33ac4178f9c4d551e3946ab480866e3cd67a65a67a4bb35367/h5py-2.9.0-cp37-cp37m-manylinux1_x86_64.whl
> Collecting marshmallow<3,>=2.16.3 (from qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/cf/b4/8dba044bc512583845aa83f7e3a988bda8df2ca4263dc9326927aea17f50/marshmallow-2.18.1-py2.py3-none-any.whl
> Collecting ply>=3.10 (from qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
> Collecting requests>=2.19 (from qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
> Collecting networkx>=2.2 (from qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
> Collecting pillow>=4.2.1 (from qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/ae/2a/0a0ab2833e5270664fb5fae590717f867ac6319b124160c09f1d3291de28/Pillow-5.4.1-cp37-cp37m-manylinux1_x86_64.whl
> Collecting marshmallow-polyfield<4,>=3.2 (from qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/fa/ba/6406b8cce3e42b2838d234310c3605627083bbb8f71dcc312c616480fe92/marshmallow_polyfield-3.2-py2.py3-none-any.whl
> Collecting requests-ntlm>=1.1.0 (from qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/03/4b/8b9a1afde8072c4d5710d9fa91433d504325821b038e00237dc8d6d833dc/requests_ntlm-1.1.0-py2.py3-none-any.whl
> Collecting mpmath>=0.19 (from sympy>=1.3->qiskit-aqua->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 2))
>   Using cached https://files.pythonhosted.org/packages/ca/63/3384ebb3b51af9610086b23ea976e6d27d6d97bf140a76a365bd77a3eb32/mpmath-1.1.0.tar.gz
> Requirement already satisfied: six in /home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages (from h5py->qiskit-chemistry->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 3)) (1.12.0)
> Collecting urllib3<1.25,>=1.21.1 (from requests>=2.19->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
> Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.19->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
> Requirement already satisfied: certifi>=2017.4.17 in /home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages (from requests>=2.19->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1)) (2018.11.29)
> Collecting idna<2.9,>=2.5 (from requests>=2.19->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
> Requirement already satisfied: decorator>=4.3.0 in /home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages (from networkx>=2.2->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1)) (4.3.2)
> Collecting cryptography>=1.3 (from requests-ntlm>=1.1.0->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/98/71/e632e222f34632e0527dd41799f7847305e701f38f512d81bdf96009bca4/cryptography-2.5-cp34-abi3-manylinux1_x86_64.whl
> Collecting ntlm-auth>=1.0.2 (from requests-ntlm>=1.1.0->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/8e/5b/4047779fb456b0de503c4acb7b166becf2567efb772abb53998440791d3c/ntlm_auth-1.2.0-py2.py3-none-any.whl
> Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/fc/32/bf446f299e5ae3315e1cc3ec2f4ae668a5424a5e1d29b78562016eecc951/cffi-1.12.1-cp37-cp37m-manylinux1_x86_64.whl
> Collecting asn1crypto>=0.21.0 (from cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
> Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.3->requests-ntlm>=1.1.0->qiskit-terra<0.8,>=0.7->qiskit->-r /home/joel/Dropbox/jupyter/qiskit/qiskit-tutorials-0.7.0/condaenv._igs7f7y.requirements.txt (line 1))
>   Using cached https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz
> Building wheels for collected packages: qiskit, sympy, psutil, mpmath, pycparser
>   Building wheel for qiskit (setup.py) ... done
> Exception:
> Traceback (most recent call last):
>   File "/home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
>     status = self.run(options, args)
>   File "/home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 355, in run
>     session=session, autobuilding=True
>   File "/home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/pip/_internal/wheel.py", line 980, in build
>     python_tag=python_tag,
>   File "/home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/pip/_internal/wheel.py", line 813, in _build_one
>     python_tag=python_tag)
>   File "/home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/pip/_internal/wheel.py", line 821, in _build_one_inside_env
>     wheel_path = builder(req, temp_dir.path, python_tag=python_tag)
>   File "/home/joel/anaconda3/envs/Qiskitenv/lib/python3.7/site-packages/pip/_internal/wheel.py", line 898, in _build_one_legacy
>     return os.path.join(tempd, sorted(os.listdir(tempd))[0])
> IndexError: list index out of range
> 
> CondaValueError: pip returned an error
> 
>

**Comment by rraymondhp** [comment]
Hi, 
This is caused by the latest `pip` which is not compatible with the latest `qiskit`.  There are two options:
(1) Install qiskit version 0.7.1 by issuing `pip install qiskit==0.7.1`

(2) downgrade the pip and install the latest qiskit. This is discussed here: 
https://github.com/Qiskit/qiskit/issues/78

Hope this solves your problem.

**Comment by rraymondhp** [comment]
Hi,
qiskit version 0.7.3 has just been released and it should not have the installation problem. Please reopen if you still have the problem.
