### ISSUE TITLE
shor_algorithm runtime errors on quantum processors

### ISSUE THREAD

**Issue by p-neumann** [Qiskit/qiskit-tutorials#536]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

**Comment by p-neumann** [comment]
shor_algorithm reported error running on either ibmqx4 or ibmq_16_melbourne. It runs fine with simulators (local and remote). Here are the errors:

---------------------------------------------------------------------------
MapperError                               Traceback (most recent call last)
<ipython-input-14-965010f2f54b> in <module>
      4 #backend = IBMQ.get_backend('ibmq_qasm_simulator')
      5 #backend = BasicAer.get_backend('qasm_simulator')
----> 6 sim_job = execute([shor], backend)
      7 sim_result = sim_job.result()
      8 sim_data = sim_result.get_counts(shor)

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/tools/compiler.py in execute(circuits, backend, config, basis_gates, coupling_map, initial_layout, shots, max_credits, seed, qobj_id, skip_transpiler, seed_mapper, pass_manager, memory, **kwargs)
    106                    config, basis_gates, coupling_map, initial_layout,
    107                    shots, max_credits, seed, qobj_id,
--> 108                    skip_transpiler, seed_mapper, pass_manager, memory)
    109 
    110     return backend.run(qobj, **kwargs)

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/tools/compiler.py in compile(circuits, backend, config, basis_gates, coupling_map, initial_layout, shots, max_credits, seed, qobj_id, skip_transpiler, seed_mapper, pass_manager, memory)
     59 
     60     circuits = transpiler.transpile(circuits, backend, basis_gates, coupling_map, initial_layout,
---> 61                                     seed_mapper, pass_manager)
     62 
     63     # step 4: Making a qobj

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/transpiler/_transpiler.py in transpile(circuits, backend, basis_gates, coupling_map, initial_layout, seed_mapper, pass_manager)
     65                                          'initial_layout': initial_layout,
     66                                          'seed_mapper': seed_mapper,
---> 67                                          'pass_manager': pass_manager})
     68     if return_form_is_single:
     69         return circuits[0]

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
     91     """
     92     if len(values) == 1:
---> 93         return [task(values[0], *task_args, **task_kwargs)]
     94 
     95     Publisher().publish("terra.parallel.start", len(values))

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/transpiler/_transpiler.py in _transpilation(circuit, backend, basis_gates, coupling_map, initial_layout, seed_mapper, pass_manager)
    107                               format='dag',
    108                               seed_mapper=seed_mapper,
--> 109                               pass_manager=pass_manager)
    110 
    111     out_circuit = dag_to_circuit(final_dag)

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/transpiler/_transpiler.py in transpile_dag(dag, basis_gates, coupling_map, initial_layout, format, seed_mapper, pass_manager)
    197             dag = Unroller(['u1', 'u2', 'u3', 'id', 'cx']).run(dag)
    198             # Simplify single qubit gates
--> 199             dag = Optimize1qGates().run(dag)
    200             logger.info("post-mapping properties: %s",
    201                         dag.properties())

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/transpiler/passes/optimize_1q_gates.py in run(self, dag)
     51                         or node["qargs"][0] != run_qarg
     52                         or left_name not in ["u1", "u2", "u3", "id"]):
---> 53                     raise MapperError("internal error")
     54                 if left_name == "u1":
     55                     left_parameters = (N(0), N(0), node["op"].param[0])

MapperError: 'internal error'

**Comment by rraymondhp** [comment]
What `shor_algorithm` did you run? The one in the tutorial?

**Comment by p-neumann** [comment]
Yes. under community->algorithms

**Comment by rraymondhp** [comment]
It is related to a bug in combining multiple 1-qubit gates into one 1-qubit gate, as here: 
https://github.com/Qiskit/qiskit-terra/issues/1478
I am closing it as it is a known bug that will be fixed.

**Comment by p-neumann** [comment]
New errors after modifying the transpiler.py file:
gaierror                                  Traceback (most recent call last)
~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/connection.py in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
    160 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     56 
---> 57     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     58         af, socktype, proto, canonname, sa = res

~/.conda/envs/qiskit_env/lib/python3.7/socket.py in getaddrinfo(host, port, family, type, proto, flags)
    747     addrlist = []
--> 748     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    749         af, socktype, proto, canonname, sa = res

gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    342         try:
--> 343             self._validate_conn(conn)
    344         except (SocketTimeout, BaseSSLError) as e:

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
    838         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
--> 839             conn.connect()
    840 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/connection.py in connect(self)
    300         # Add certificate verification
--> 301         conn = self._new_conn()
    302         hostname = self.host

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/connection.py in _new_conn(self)
    167             raise NewConnectionError(
--> 168                 self, "Failed to establish a new connection: %s" % e)
    169 

NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f02864c2f98>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~/.conda/envs/qiskit_env/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    637             retries = retries.increment(method, url, error=e, _pool=self,
--> 638                                         _stacktrace=sys.exc_info()[2])
    639             retries.sleep()

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    397         if new_retry.is_exhausted():
--> 398             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    399 

MaxRetryError: HTTPSConnectionPool(host='quantumexperience.ng.bluemix.net', port=443): Max retries exceeded with url: /api/Jobs/5c770a5849b0210062e9cb4c/status?access_token=dTt7mlpOPYvGNMHuHR2ziBQv2UydwCSjRV9QpDIQ0wozzz8CW07h1PGFeafmIedL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f02864c2f98>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqjob.py in status(self)
    266             # TODO: See result values
--> 267             api_job = self._api.get_status_job(self._job_id)
    268             if 'status' not in api_job:

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/ibmq/api/ibmqconnector.py in get_status_job(self, id_job, hub, group, project, access_token, user_id)
    673 
--> 674         status = self.req.get(url)
    675 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/ibmq/api/ibmqconnector.py in get(self, path, params, with_token)
    356             response = requests.get(url, verify=self.verify, headers=headers,
--> 357                                     **self.extra_args)
    358             if not self.check_token(response):

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/requests/api.py in get(url, params, **kwargs)
     74     kwargs.setdefault('allow_redirects', True)
---> 75     return request('get', url, params=params, **kwargs)
     76 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/requests/api.py in request(method, url, **kwargs)
     59     with sessions.Session() as session:
---> 60         return session.request(method=method, url=url, **kwargs)
     61 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/requests/sessions.py in send(self, request, **kwargs)
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 

ConnectionError: HTTPSConnectionPool(host='quantumexperience.ng.bluemix.net', port=443): Max retries exceeded with url: /api/Jobs/5c770a5849b0210062e9cb4c/status?access_token=dTt7mlpOPYvGNMHuHR2ziBQv2UydwCSjRV9QpDIQ0wozzz8CW07h1PGFeafmIedL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f02864c2f98>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

JobError                                  Traceback (most recent call last)
<ipython-input-10-4441476d9f4d> in <module>
      5 #backend = Aer.get_backend('qasm_simulator')
      6 sim_job = execute([shor], backend)
----> 7 sim_result = sim_job.result()
      8 sim_data = sim_result.get_counts(shor)
      9 plot_histogram(sim_data)

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqjob.py in result(self, timeout, wait)
    201             JobError: exception raised during job initialization
    202         """
--> 203         job_response = self._wait_for_result(timeout=timeout, wait=wait)
    204         return self._result_from_job_response(job_response)
    205 

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqjob.py in _wait_for_result(self, timeout, wait)
    208 
    209         try:
--> 210             job_response = self._wait_for_job(timeout=timeout, wait=wait)
    211             if not self._qobj_payload:
    212                 self._qobj_payload = job_response.get('qObject', {})

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqjob.py in _wait_for_job(self, timeout, wait)
    387         """
    388         start_time = time.time()
--> 389         while self.status() not in JOB_FINAL_STATES:
    390             elapsed_time = time.time() - start_time
    391             if timeout is not None and elapsed_time >= timeout:

~/.conda/envs/qiskit_env/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqjob.py in status(self)
    271         # pylint: disable=broad-except
    272         except Exception as err:
--> 273             raise JobError(str(err))
    274 
    275         if api_job['status'] == 'VALIDATING':

JobError: "HTTPSConnectionPool(host='quantumexperience.ng.bluemix.net', port=443): Max retries exceeded with url: /api/Jobs/5c770a5849b0210062e9cb4c/status?access_token=dTt7mlpOPYvGNMHuHR2ziBQv2UydwCSjRV9QpDIQ0wozzz8CW07h1PGFeafmIedL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f02864c2f98>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"

**Comment by rraymondhp** [comment]
This is because the timeout is too small and when you are running it on real-device, longer timeout should be expected. Please try to run your with longer timeout, say, 
`execute(..., coupling_map=coupling_map, shots=shots,timeout=240000)`

**Comment by rraymondhp** [comment]
@p-neumann  Sorry, not on execute, but `timeout` should be set like these:
```
sim_job = execute([shor], backend)
sim_result = sim_job.result(timeout=10000)
```

**Comment by bkalapar** [comment]
the errors can be turn as functionalities of the Quantum process by adding the delay and time process, to fix the errors we can make the name spaces into  lists  or tuples of a defined dictionary,
as I have a little bit of knowledge, what is there i shared with you, if any thing wrong please forgive me
