### ISSUE TITLE
cannot import name 'get_input_instance' from 'qiskit_aqua.input'

### ISSUE THREAD

**Issue by mstypulk** [Qiskit/qiskit-tutorials#552]
### Informations

- **Qiskit version**: 0.7.2
- **Python version**: 3.7.2
- **Operating system**: MacOS 10.14

### What is the current behavior?
Error when running this line:
```from qiskit_aqua.input import get_input_instance```
in the Qiskit-aqua tutorial notebook 'vqe.ipynb'

This notebook can be found at GitHub repo: qiskit/qiskit-tutorials/community/aqua/general/vqe.ipynb

### Steps to reproduce the problem
Run the first code cell in the notebook:
```
from qiskit_aqua import Operator, run_algorithm
from qiskit_aqua.input import get_input_instance
```

### Suggested solutions
I did not see the function ```get_input_instance()``` in the Qiskit-aqua repo, nor did I find it when searching through documentation. In the vqe2iqpe.ipynb notebook (found in the same directory) ```get_input_instance()``` is not imported, and instead do ```from qiskit_aqua.input import EnergyInput``` and use ```EnergyInput()``` in a similar way.

**Comment by woodsp-ibm** [comment]
Thanks. That method was removed and it seems the notebook was not updated. Using EnergyInput directly is fine. The notebook has been updated already in a [WIP] PR in prep for Aqua version 0.5

**Comment by jonguenther** [comment]
This issue can also be found in the [notebook to TSP](https://github.com/Qiskit/qiskit-tutorials/blob/master/community/awards/teach_me_quantum_2018/TeachMeQ/Week_8-High_Level_Quantum_Programming/exercises/w8_04.ipynb) which uses the same methods.

**Comment by nonhermitian** [comment]
This is resolved
