### ISSUE TITLE
Incorporating 1903.04359 by Daniel Koch, Laura Wessing, Paul M. Alsing

### ISSUE THREAD

**Issue by lerongil** [Qiskit/qiskit-tutorials#562]
### What is the expected behavior?
[This is a great paper](https://arxiv.org/pdf/1903.04359.pdf) outlining the following lessons: 

Lesson 1 - Intro to QuantumCircuits
Lesson 2 - Creating More Complex QuantumCircuits
Lesson 3 - Gates Provided by Qiskit
Lesson 4 - Our Custom Functions
Lesson 5.1 - Intro to Quantum Algorithms (Deutsch)
Lesson 5.2 - Deutsch-Jozsa & Bernstein-Vazirani Algorithms
Lesson 5.3 - Simon’s Algorithm
Lesson 5.4 - The Grover Search.
Lesson 6 - Quantum Fourier Transformation

How do we want to support this? Assuming we have approval from the authors, would we like to convert this paper into a set of Jupyter notebooks in the main Qiskit tutorials or should we add them into the community tutorials?

**Comment by rraymondhp** [comment]
Hi,

AFAIK, all of the algorithms and explanations are already in the community and other directories.

**Comment by attp** [comment]
I think it's a great set of tutorials, but given the overlap with our tutorial content, perhaps we could see if the authors are interested in creating their own repository with the content (with our help if they want), and then we could link to it.

**Comment by lerongil** [comment]
I like the idea of creating an index for it. Will reach out to the authors to see if this is something they would consider doing. Thanks for the input @rraymondhp and @attp .

**Comment by aasfaw** [comment]
Closing this since there is an index file in the works and all the content in that paper already exists in our tutorials folder.

**Comment by chowington** [comment]
Hi, where exactly can I find the paper's content in the tutorials? Particularly their custom functions which are pretty useful. The code for these is given at the paper's appendix but is not copyable.
