### ISSUE TITLE
Ignis relaxation and decoherence tutorial no longer includes any quantum information

### ISSUE THREAD

**Issue by Travis-S** [Qiskit/qiskit-tutorials#567]
As part of 18387c083a3b816463f435f67b1943de2c1ec995, the old Ignis tutorials were removed and new ones put in. The new ones do not include any quantum information describing the noise, nor the experiments necessary to characterize it.

@dcmckayibm @jaygambetta Was this an intentional change, or should that content be added back to the new tutorials? If the latter, how much would you like to see ported over?

**Comment by dcmckayibm** [comment]
The background information was moved to community/ignis (https://github.com/Qiskit/qiskit-tutorials/tree/master/community/ignis). The idea is that the notebooks in qiskit/ignis will be more example use-cases for the code whereas the community files will be background and tutorials on the physics. 

Let me know if something is missing from there and please add as you want.

**Comment by Travis-S** [comment]
@dcmckayibm Gotcha!
