### ISSUE TITLE
Can the feature dimension be higher than 3?

### ISSUE THREAD

**Issue by XBLDev** [Qiskit/qiskit-tutorials#571]
### What is the expected behavior?

Hi

Is it possible to have a feature number higher than 3 for the svminput? In the qsvm_kernel_classification notebook it says "we support feature_dim 2 or 3", i passed n higher than 3 in my own code with some random dataset and it seems to be fine. Is this constraint only because of data visualisation or svminput just can't have more than 3 data dimension?

**Comment by nonhermitian** [comment]
This is from a while ago, and no response from @pistoia.  If @XBLDev still has some issues, please reopen.
