### ISSUE TITLE
Question about porfolio-py ising translator

### ISSUE THREAD

**Issue by moldos** [Qiskit/qiskit-tutorials#580]
It's about portfolio tutorial
I have question with regards on how the operator is build - function get_porfolio_qubuitops inside portfolio.py ising translator, namely the following line (operator construction):
pauli_list.append([2*sigma_z[i_, j_], Pauli(zp, xp)])
Question is: why factor/number 2 there. It beats me. If you are so kind to explain, I would be grateful.
Thank you.

**Comment by stefan-woerner** [comment]
The for-loops for i, j originally both run over range(n).
However, the case i == j is can be handled separately, since it gives a constant term (z in {-1, +1} => z^2==1).
Instead of catching i == j, and since z_i * z_j == z_j * z_i, we just run the for-loops for i < j and multiply every term by 2.

**Comment by moldos** [comment]
Understood. Clear picture. Many thanks
