### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by imvieira** [Qiskit/qiskit-tutorials#582]
Eight months ago was published the Getting Start Video for Qiskit on YouTube. Click here to watch: https://www.youtube.com/watch?v=V3hXSftZuoc

So I did pip install jupyter , qiskit and msgpack. Then, I ran the Jupyter Notebook and simulated the video tutorial. But I do not know how to solve the following error

 ![Screen Shot 2019-04-03 at 20 41 47](https://user-images.githubusercontent.com/13357603/55520077-0c499780-5651-11e9-9aab-38f873feec02.png)
![Screen Shot 2019-04-03 at 20 41 55](https://user-images.githubusercontent.com/13357603/55520078-0c499780-5651-11e9-807a-99f5d7ad4d0b.png)

**Comment by aasfaw** [comment]
Replace the last line with these two:

```
backend = qk.BasicAer.get_backend('qasm_simulator')
job_1 = qk.execute([test_Z,test_X],backend=backend,shots=1000) 
```

and please let us know if you have any more issues.

**Comment by rraymondhp** [comment]
Hi,
I suspect you are using older version of qiskit. Please upgrade your qiskit and use backend not by string, but by passing an object of backend as follows:
```
backend_sim = BasicAer.get_backend('statevector_simulator')
result = execute(circ2, backend_sim).result()
states = result.get_statevector(circ2)

backend_sim = BasicAer.get_backend('qasm_simulator')
result = execute(qc2, backend_sim).result()
counts = result.get_counts(qc2)

backend_sim = BasicAer.get_backend('unitary_simulator')
result = execute(circ2, backend_sim).result()
unitary = result.get_unitary(circ2)
```

You can see more details here:
https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/quantum_circuits.ipynb

**Comment by rraymondhp** [comment]
Hi,
I am closing this issue because @aasfaw reply should solve the issue. Please reopen if you still encounter this.
