### ISSUE TITLE
Got a 400 code response to /api/Jobs: {"error":{"status":400,"message":"Generic error","code":"GENERIC_ERROR"}} In [23]:

### ISSUE THREAD

**Issue by imvieira** [Qiskit/qiskit-tutorials#585]
`Got a 400 code response to /api/Jobs: {"error":{"status":400,"message":"Generic error","code":"GENERIC_ERROR"}}`
 
![Screen Shot 2019-04-07 at 09 53 15](https://user-images.githubusercontent.com/13357603/55683873-025ab980-591b-11e9-9749-aaeb4a78912e.png)

**Comment by nonhermitian** [comment]
The generic error 400 is a connection error. This indicates that the connection to the servers has been dropped, or cannot be established. This happens sometimes, and work to make it never happen is on going.
