### ISSUE TITLE
Tutorials need copyright statement

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-tutorials#593]
### What is the expected behavior?
Tutorials should include the following copyright statement (preferably at the bottom to avoid clutter):

```python

# This code is part of Qiskit.
#
# (C) Copyright IBM 2017, XXXX.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.
```
where `XXXX` is the year of the tutorial in question.

**Comment by jaygambetta** [comment]
how do you suggest doing this.

**Comment by nonhermitian** [comment]
The same header we have in the source as markdown text at the bottom of each example.

**Comment by aasfaw** [comment]
@nonhermitian this can get a little complicated since we have community-contributed tutorials as well. what is the goal of adding this to tutorials?

**Comment by nonhermitian** [comment]
So the issue here is that we have had our tutorials stripped of their qiskit identification, and represented by others as their own work.  At present we list this repo as being under Apache 2, but only in the readme.  So if someone is pointed to a file from some other location, there is no license information available to indicate that the files are under Apache.  The community contributed ones are still under this license as they have signed the CLA.  So the recommendation would be to put the license footer on all notebooks, just like all source code contributions to qiskit must have the IBM Apache 2 header in them.

**Comment by aasfaw** [comment]
Thanks for explaining @nonhermitian. @jaygambetta this makes sense to me -- I can add the Apache 2 footer if we have consensus. What do you think?

**Comment by quantumjim** [comment]
If this is implemented, we'd need to tell external contributors to add to it their pull request. I would expect that this might put people off from contributing (even though it just restates what they agreed to in the CLA), since it seems to give IBM credit for their work.

Is there any possibility that contributors could alter it slightly? For example, replacing the first line with

    # This code is part of Qiskit. The original version was written by blah blah blah.
    #
    # (C) Copyright IBM 2017, XXXX.
    #
    # This code is licensed under the Apache License, Version 2.0. You may
    # obtain a copy of this license in the LICENSE.txt file in the root directory
    # of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
    #
    # Any modifications or derivative works of this code must retain this
    # copyright notice, and modified files need to carry a notice indicating
    # that they have been altered from the originals.

**Comment by kenixer** [comment]
I want to use [Quantum_Cryptography2.ipynb](https://github.com/Qiskit/qiskit-tutorials/blob/master/community/awards/teach_me_qiskit_2018/quantum_cryptography_qkd/Quantum_Cryptography2.ipynb)'s Algorithm in my project. So basically, I want to change, modify, and implement it to my software. How should I include the license? For addition, I'm planning to upload my software to github, with MIT License.

**Comment by quantumjim** [comment]
Hi @kenixer. [Here](https://github.com/Qiskit/qiskit-tutorials/blob/master/LICENSE) is the license. The most important part is probably

>  4. Redistribution. You may reproduce and distribute copies of the
>       Work or Derivative Works thereof in any medium, with or without
>       modifications, and in Source or Object form, provided that You
>       meet the following conditions:
> 
>       (a) You must give any other recipients of the Work or
>           Derivative Works a copy of this License; and
> 
>       (b) You must cause any modified files to carry prominent notices
>           stating that You changed the files; and
> 
>       (c) You must retain, in the Source form of any Derivative Works
>           that You distribute, all copyright, patent, trademark, and
>           attribution notices from the Source form of the Work,
>           excluding those notices that do not pertain to any part of
>           the Derivative Works; and
> 
>       (d) If the Work includes a "NOTICE" text file as part of its
>           distribution, then any Derivative Works that You distribute must
>           include a readable copy of the attribution notices contained
>           within such NOTICE file, excluding those notices that do not
>           pertain to any part of the Derivative Works, in at least one
>           of the following places: within a NOTICE text file distributed
>           as part of the Derivative Works; within the Source form or
>           documentation, if provided along with the Derivative Works; or,
>           within a display generated by the Derivative Works, if and
>           wherever such third-party notices normally appear. The contents
>           of the NOTICE file are for informational purposes only and
>           do not modify the License. You may add Your own attribution
>           notices within Derivative Works that You distribute, alongside
>           or as an addendum to the NOTICE text from the Work, provided
>           that such additional attribution notices cannot be construed
>           as modifying the License.
> 
>       You may add Your own copyright statement to Your modifications and
>       may provide additional or different license terms and conditions
>       for use, reproduction, or distribution of Your modifications, or
>       for any such Derivative Works as a whole, provided Your use,
>       reproduction, and distribution of the Work otherwise complies with
>       the conditions stated in this License.

**Comment by kenixer** [comment]
Well, I created `NOTICE` directory in my repo, and copied this repo's `LICENSE` file in that directory, and added the comment in the code which says that I modified them. Isn't that enough?

**Comment by nonhermitian** [comment]
This is done.
