### ISSUE TITLE
Using Shor's algorithm to solve discrete logarithm problem

### ISSUE THREAD

**Issue by imvieira** [Qiskit/qiskit-tutorials#602]
### What is the expected behavior?

I have read about Shor's algorithm and my understanding is that it can be used to factor large numbers efficiently. Can Shor's algorithm, though, be used to solve this problem:

Find the number 𝑒 e  given the following information (Assume that 𝑃 P , 𝐶 C , 𝑁 N  and 𝑒 e  are all large, say 2048-bit integers):  the integers 𝑃 P  and 𝑁 N the integer 𝐶 C  where 𝐶=𝑃𝑒mod𝑁 C = P e mod N If so, how does this algorithm work? 

Please explain it simply how can I solve this problem or a similar one using qiskit, as I am not familiar with quantum mechanics.

**Comment by aasfaw** [comment]
@imvieira both discrete log and factoring can solved by taking advantage of the hidden periodicity in the structure of the problems. Shor's algorithm works for both. You can find a description of Shor's algorithm, particularly as it relates to solving the factoring problem, in [the tutorial here](https://github.com/Qiskit/qiskit-tutorials/blob/master/community/algorithms/shor_algorithm.ipynb).

By the way, your question is copied word for word [from this crypto stack exchange question](https://crypto.stackexchange.com/questions/37018/using-shors-algorithm-to-solve-the-discrete-logarithm-problem). I am not sure why you are doing this. The answer there is also something you should read in case you are really curious, and please note that your question isn't an issue with the tutorials, nor does it deserve the tag "enhancement" that you have attached to it.
