### ISSUE TITLE
.get_count() returns weird output when I run circuit on the real backend

### ISSUE THREAD

**Issue by gaoning041x** [Qiskit/qiskit-tutorials#608]
### Informations

- **Qiskit version**: 0.6.1
- **Python version**: 3.5.2
- **Operating system**: Ubuntu(64-bit)

### What is the current behavior?

I'm working on a circuit that has now 7 qubits and 3 classical bits, it works fine on the simulator, i.e I got counts of the classical bits (like 000, 001, ...). But when I try the circuit on the real backend (16 bits machine), the .get_count() method would just return {'0x4': 217, '0x2': 269, '0x6': 206, '0x1': 1971, '0x7': 1692, '0x3': 1838, '0x5': 1735, '0x0': 264}
May I ask, what does these 0x1, 0x2 ...mean? Are they just the usual 001, 002 ...? How should I interpret the results?

**Comment by nonhermitian** [comment]
Your version of qiskit is too old.  You need qiskit 0.8 or higher installed: `pip install qiskit`

**Comment by gaoning041x** [comment]
Hi, @nonhermitian thank you for your answer. I'm trying to update the qiskit, but when I'm using the new version, I find that somehow, I receive errors such as:
Traceback (most recent call last):
  File "quantum2.py", line 6, in <module>
    from qiskit import available_backends, execute, register, get_backend
ImportError: cannot import name 'available_backends'

Can you please also help me with this?

**Comment by nonhermitian** [comment]
Your code us also for the older software version. You need to update. It is probably best to go through the tutorials in this repo to see what needs to be changed.

**Comment by gaoning041x** [comment]
Got it, will work on it. Thanks a lot.
