### ISSUE TITLE
what is goal for community/exercise

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-tutorials#617]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

@aasfaw what is the goal for the community/exercise folder 

### Suggested solutions

remove or make this folder clearer

**Comment by rraymondhp** [comment]
Hi @jaygambetta 
I added this folder for notebooks that contain exercises corresponding to each tutorial we have.

**Comment by jaygambetta** [comment]
ok work with @aasfaw, @attp, and @quantumjim to make it feel like more than one random tutorial.
