### ISSUE TITLE
Add release new features to community/releases folder 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-tutorials#624]
### What is the expected behavior?

For qiskit 0.6 and qiskit 0.7 we released notebooks showing the changes. Do we want to keep this up. If so we need to add it for 0.8 and the recent 0.9 release.

**Comment by jaygambetta** [comment]
Also for completeness I would rename this notebooks qiskit over terra.

**Comment by lerongil** [comment]
I will ask a few of our users through Q summit to see if they saw these release notebooks and, if so,  found them useful. My guess is we might have too much content around releases (blog, new notebooks, change log, release history) and this might be lost in the release process. This is just my guess and I'd like to confirm or deny it.

**Comment by jaygambetta** [comment]
sounds good

**Comment by aasfaw** [comment]
@lerongil should we keep the releases folder?

**Comment by aasfaw** [comment]
I'm going to close this. As Leron said, there are many avenues where this information is duplicated. We have release announcements on medium stating the changes, and our tutorials are usually updated to keep track of the changes. Also, release notes are available in qiskit documentation.

**Comment by jaygambetta** [comment]
Then why should we keep it. If we are not going to update I would remove the folder all together

**Comment by lerongil** [comment]
Forgot to post the follow up here. I spoke to a few folks at Q summit and no one used these release tutorials. This is not to say that they are not useful but they might not be communicated well. I would suggest removing this folder and focusing on our current process of releases: 

Blog Post highlighting updates 
Updated qiskit-tutorials/qiskit 
Changelog 
Communication via Twitter/Slack

The more resources we add the harder it will be to parse through all of it.

**Comment by aasfaw** [comment]
Agreed, let's remove the folder.
