### ISSUE TITLE
two_qubit_kak is deprecated

### ISSUE THREAD

**Issue by ismaelfaro** [Qiskit/qiskit-tutorials#629]
### Informations

- **Qiskit version**: 0.10
- **Python version**:  3.6.2
- **Operating system**: OSX

### What is the current behavior?
in the tutorial " [terra/terra_parallel_tools.ipynb](https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/terra_parallel_tools.ipynb)" the line:
 
`from qiskit.quantum_info.synthesis import two_qubit_kak`

return the error: *ImportError: cannot import name ‘two_qubit_kak’ from ‘qiskit.quantum_info.synthesis’*

### Suggested solutions

Remove the line and adapt the tutorial.

**Comment by AshhChika** [comment]
I am also suffering from this problem on IBMQ Experience notebook.

Qiskit version: 0.8.2
Operating system: OSX

**Comment by nonhermitian** [comment]
Yes, that is being updated soon

**Comment by mtreinish** [comment]
Oh, I didn't see this I already pushed a fix for it in: https://github.com/Qiskit/qiskit-tutorials/pull/774

**Comment by jaygambetta** [comment]
closing with #774
