### ISSUE TITLE
I want the tutorial of quantum GAN

### ISSUE THREAD

**Issue by UdonDa** [Qiskit/qiskit-tutorials#636]
### What is the expected behavior?
There are quantum GAN implementations in https://github.com/Qiskit/qiskit-aqua/tree/6004d524c0434cd304ab0472bb7f513b4147a9fb/qiskit/aqua/components/neural_networks. 
But, I do not know how to use this implementation.
So, I hope one makes the tutorial.

**Comment by woodsp-ibm** [comment]
There are updated and new tutorials that have been done the Aqua 0.5 release that includes qGAN. They are in PRs here pending imminent approval/merging here. The relevant one is `Aqua 0.5 update for qiskit tutorials #633` and the tutorial will be in folder `qiskit/finance/machine_learning`. 
If you wish, while the approval/merge is pending, you can see the tutorial already on the fork of the repo in the PR where we have done the changes and additions. It is here
https://github.com/manoelmarques/qiskit-tutorials/tree/for-aqua0.5-qiskit/qiskit/finance/machine_learning

**Comment by UdonDa** [comment]
@woodsp-ibm 
Could I ask you?
Where is the training code?
I see your paper and think that this qgan is trained with both quantum generator and classical discriminator.

**Comment by woodsp-ibm** [comment]
Did you look at this tutorial here?
https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/artificial_intelligence/qgans_for_loading_random_distributions.ipynb

**Comment by UdonDa** [comment]
I miss it.
Thanks!!
