### ISSUE TITLE
Terra Advanced Circuits tutorial link  - 404

### ISSUE THREAD

**Issue by nubbyOne** [Qiskit/qiskit-tutorials#640]
### Informations

- **Qiskit version**: 0.9
- **Python version**: 3.6
- **Operating system**: macOS

### What is the current behavior?
New features tutorial for Advanced Circuit cannot be found 404
https://nbviewer.jupyter.org/github/Qiskit/qiskit-tutorials/blob/master/qiskit/qiskit/terra/advanced_circuits.ipynb

### Steps to reproduce the problem
Follow link above

### What is the expected behavior?
.ipynb is found

### Suggested solutions
Provide the correct link

**Comment by kdk** [comment]
Hi @nubbyOne , thanks for reporting this! #641 should correct the link to point to https://nbviewer.jupyter.org/github/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/advanced_circuits.ipynb
