### ISSUE TITLE
some question about reset operation 

### ISSUE THREAD

**Issue by pittcat** [Qiskit/qiskit-tutorials#672]
### Informations

- **Qiskit version**:
0.10
- **Python version**:
3.7
- **Operating system**:
arch linux 
### What is the current behavior?

![reset_test](https://user-images.githubusercontent.com/22888402/57926508-0eed0d00-78de-11e9-9974-67930e6c77a3.png)
As the picture shows,when i execute the circuit on qasm_simulator or ibmq_qasm_simulator ,it works well.But if i excute circuit on ibmqx2 ,ibmq_16_melbourne or ibmqx4,it will report an error.

### Steps to reproduce the problem
```
from qiskit import QuantumCircuit, QuantumRegister,ClassicalRegister
from qiskit import execute, BasicAer
from time import time
from qiskit import IBMQ
from qiskit.tools.monitor import job_monitor

q=QuantumRegister(5,'q')
c=ClassicalRegister(5,'c')
circuit=QuantumCircuit(q)

circuit.x(q[0])
circuit.cx(q[0],q[1])
circuit.cx(q[0],q[3])
circuit.barrier()
circuit.reset(q[1])
circuit.draw(output='mpl')

circuit.add_register(c)
circuit.measure(q,c)
circuit.draw(output='mpl')

# + {"run_control": {"marked": true}}
shot_times=1
max_credits=3
# IBMQ.load_accounts()
# backend=IBMQ.get_backend('ibmq_qasm_simulator')
backend=BasicAer.get_backend('qasm_simulator')
start=time()
start
job_exp = execute(circuit, backend, shots=shot_times, max_credits=max_credits)
job_monitor(job_exp)
end=time()
print(end-start)
result=job_exp.result()
end=time()
print(end-start)
counts = result.get_counts(circuit)
# -

from qiskit.tools.visualization import plot_histogram
plot_histogram(counts)

```

### What is the expected behavior?
I want to know whether the reset operation works but currently only in simulation.Can the reset operation work on ibmq_poughkeepsie or ibmq_20_tokyo?

**Comment by nonhermitian** [comment]
Reset operations are not currently supported on the devices. Only simulators at present.

**Comment by pittcat** [comment]
@nonhermitian Thanks for your reply.Is it possible to achieve in the future?I would appreciate it very much if you can share me some paper about the achievement of reset operation just by link.

**Comment by nonhermitian** [comment]
I can not speak to future work.  However, the devices are constantly improving.
