### ISSUE TITLE
IQX Broken link optimization notebook

### ISSUE THREAD

**Issue by nubbyOne** [Qiskit/qiskit-tutorials#678]
### Informations
IQX beta
- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
Borken link

### Steps to reproduce the problem

Go here:
https://quantum-computing.ibm.com/jupyter/tutorial/optimization/index.ipynb

Click this: "Solve classical optimization (Max-Cut and Traveling Salesman Problem)"

### What is the expected behavior?
Link works

### Suggested solutions

Fix link

**Comment by nubbyOne** [comment]
Most (all?) the links in this notebook are broken ... probably because the repo name was changed

https://github.com/Qiskit/qiskit-tutorials/blob/master/community/aqua/index.ipynb

**Comment by aasfaw** [comment]
@nubbyOne can you please explain? I'm clicking the link that you are referring to (the Max-Cut and TSP notebook) and it works fine for me. Can you please double-check?

**Comment by aasfaw** [comment]
This issue has been fixed. Thank you for reporting, @nubbyOne.
