### ISSUE TITLE
Terra using_the_transpiler tutorial | transpile circuit drawing is confusing for StochasticSwap pass

### ISSUE THREAD

**Issue by fvarchon** [Qiskit/qiskit-tutorials#679]
### Informations

- **Qiskit version**: 0.10.1
- **Python version**: 3.7.3
- **Operating system**: windows 10

### What is the current behavior?

Two problems in **Different Variants of the Same Pass** part:
1/ The initial look of the tutorial show drawing of circuit in color. Executing each cell results in a black-and-white representation as style is never defined in this notebook. Not a big problem

2/ stochastic_circ.draw(output='mpl') :
Initial look :
![image](https://user-images.githubusercontent.com/37110948/58105220-693fe380-7be6-11e9-8406-e33d3e81c823.png)

After executing this cell:
![image](https://user-images.githubusercontent.com/37110948/58105285-85dc1b80-7be6-11e9-9654-db3c1ce1c1b4.png)

The result is confusing as after executing the cell we obtain something different and which moreover seems in contradiction with the defined coupling map. 

For example despite a coupling map defined like (coupling = [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6]]) (no direct link between 0 and 6) we obtain a first CNOT between qubits 0 and 6. I assume there is a change in layout but as it is never explicit it could be confusing.

**Comment by nonhermitian** [comment]
Yes, the StochasticSwap returns the circuit in the virtual qubit space of the circuit.  As opposed to the physical space on the device.  See for example #1831.

**Comment by ajavadia** [comment]
https://github.com/Qiskit/qiskit-terra/pull/2463 should fix this.

the style was made "color" by default after the release. so with the pip release you will get black and white.

**Comment by nonhermitian** [comment]
This should now be resolved
