### ISSUE TITLE
Unable to display qubit properties on "ibmq_20_tokyo" backend

### ISSUE THREAD

**Issue by revilooliver** [Qiskit/qiskit-tutorials#706]
### Informations

- **Qiskit version**: 0.8.0
- **Python version**: 3.7.3
- **Operating system**: Windows(64_bit)

### What is the current behavior?

I tried to monitor the device information and qubit properties use the following lines:

from qiskit.tools.jupyter import *
%qiskit_backend_monitor device

It works correctly on the "ibmq_poughkeepsie" backend, but for the "ibmq_20_tokyo" backend it is giving me this error message:
KeyError                                  Traceback (most recent call last)
<ipython-input-7-7bcc9d3b1ae5> in <module>
      1 from qiskit.tools.jupyter import *
----> 2 get_ipython().run_line_magic('qiskit_backend_monitor', 'device')

E:\lab\quantum_computing\anaconda\envs\Qiskitenv\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2306             with self.builtin_trap:
-> 2307                 result = fn(*args, **kwargs)
   2308             return result
   2309 

<E:\lab\quantum_computing\anaconda\envs\Qiskitenv\lib\site-packages\decorator.py:decorator-gen-806> in qiskit_backend_monitor(self, line, cell)

E:\lab\quantum_computing\anaconda\envs\Qiskitenv\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

E:\lab\quantum_computing\anaconda\envs\Qiskitenv\lib\site-packages\qiskit\tools\jupyter\backend_monitor.py in qiskit_backend_monitor(self, line, cell)
     59             tab_contents.extend(['Qubit Properties', 'Multi-Qubit Gates',
     60                                  'Error Map', 'Job History'])
---> 61             details.extend([qubits_tab(backend), gates_tab(backend),
     62                             detailed_map(backend), job_history(backend)])
     63 

E:\lab\quantum_computing\anaconda\envs\Qiskitenv\lib\site-packages\qiskit\tools\jupyter\backend_monitor.py in gates_tab(backend)
    296     for qub in range(left_num):
    297         gate = multi_qubit_gates[qub]
--> 298         name = gate['name']
    299         ttype = gate['gate']
    300         error = round(gate['parameters'][0]['value'], 5)

KeyError: 'name'

By the way, the "ibmq_20_tokyo" backend sometimes gives me this error message when I'm executing a job:
qiskit.backends.joberror.JobError: 'Invalid job state. The job should be DONE but it is JobStatus.ERROR'
Meanwhile, the same job can be executed correctly on "ibmq_poughkeepsie".

### Steps to reproduce the problem

Just run the following program, then supposedly the error message will come out. 
from qiskit import IBMQ
IBMQ.enable_account('...')
from qiskit import *
from qiskit.compiler import transpile
from qiskit.visualization import plot_histogram
from qiskit.tools.monitor import job_monitor
IBMQ.load_accounts()
%matplotlib inline
device = IBMQ.get_backend('ibmq_20_tokyo')
from qiskit.tools.jupyter import *
%qiskit_backend_monitor device

### What is the expected behavior?
In expectation, it should print the device information like this:
![image](https://user-images.githubusercontent.com/28457462/58828750-22091800-8614-11e9-9252-58fbd945b740.png)

### Suggested solutions

I need help with this.

**Comment by nonhermitian** [comment]
It looks like the device was returning ill-formated data for a bit.  This now appears to be resolved.
