### ISSUE TITLE
Placement and coverage of index files

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-tutorials#722]
The index was moved in #621 to become dedicated to the community folder (which also led to the issue in #721).

I think it is import to index the entire repository. If someone wants to look up how to use a given command, for example, it is good for them to be pointed to its uses in the qiskit folder as well as the community folder.

I suggest that we move indexer.py and index.md back out to the top level, and link to them in README.md. The embedding of index.md into community/index.ipynb can then be removed.

**Comment by jaygambetta** [comment]
closing as now its in the community tutorial repository
