### ISSUE TITLE
library pyeda required for grover

### ISSUE THREAD

**Issue by marisvs** [Qiskit/qiskit-tutorials#727]
### Information

- **Qiskit 0.10.4**:
- **Python 3.7.1**:
- **Windows 10**:

### What is the current behavior?
The notebook community/optimization/grover.ipynb gives an error after the command 
```
oracle = LogicalExpressionOracle(input_3sat_instance)
```
an error message appears that ends with:
AquaError: "Unable to instantiate 'LogicalExpressionOracle', pyeda is not installed. Please look at https://pyeda.readthedocs.io/en/latest/install.html."

### Steps to reproduce the problem
Run the grover.ipynb notebook

### What is the expected behavior?
This command should not give an error

### Suggested solutions
Arrange the pyeda library included as prereq as well.

**Comment by woodsp-ibm** [comment]
The pydea library cannot be included in the pre-reqs for Windows as there is not an install package that the author provides to do this. The link provided does however have an install section for Windows.

**Comment by marisvs** [comment]
Suggestion: perhaps add a statement in notebooks where required to warn the user about this pyeda problem

**Comment by nonhermitian** [comment]
`pyeda` is no longer required.
