### ISSUE TITLE
Qubit calibration tutorial needs update

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-tutorials#744]
[calibrating_a_qubit](https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/calibrating_a_qubit.ipynb) tutorial is written in old style.

- need update for API v2.
- measurement pulse is now provided by backend
- bug of duplicated figure ouput has fixed (no need of substitution)
- using `union` instead of `append` is safer (now many commands include additional FCs on u-channels and sometime they cause unintended behavior with `append`)
- DeviceSpecification is replaced by PulseChannelSpec (see #735 and will be solved by #736)

these updates should be applied after #736 is mergerd.

**Comment by nonhermitian** [comment]
#736  has been merged
