### ISSUE TITLE
Fix notebook of Hamiltonian and Gate Characterization

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-tutorials#750]
### Informations

- **Qiskit version**: master
- **Python version**: 3.6.5
- **Operating system**: Linux

### What is the current behavior?

Some outputs are very different from the notebook that's in the repository.

![image](https://user-images.githubusercontent.com/22316088/62453469-0ee10880-b77b-11e9-8533-23f630fa0c8e.png)

![image](https://user-images.githubusercontent.com/22316088/62453501-1dc7bb00-b77b-11e9-8fe2-bbda45fb39fd.png)

**Comment by dcmckayibm** [comment]
https://github.com/Qiskit/qiskit-ignis/issues/237

We need to force optimization_level 0 into these or add barriers to the circuit

**Comment by dcmckayibm** [comment]
Added barriers https://github.com/Qiskit/qiskit-ignis/pull/245, should be able to close this

**Comment by yaelbh** [comment]
Indeed fixed, closing
