### ISSUE TITLE
Update notebooks with the new IBMQProvider

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-tutorials#751]
What are the instructions for using a local clone of the newest IBMQProvider?  I cloned qiskit-ibmq-provider and am referring to the clone with my PYTHONPATH, nevertheless the code goes to the installed version of ibmq.

**Comment by nonhermitian** [comment]
I think this is more of a question for the docs in https://github.com/Qiskit/qiskit as the tutorials assume the user has installed qiskit.

**Comment by yaelbh** [comment]
I need the instructions for myself. I'm trying to adjust Aer and Ignis notebooks to the IBMQ provider that's in the master branch. But I don't know how to run these revised notebooks.

**Comment by nonhermitian** [comment]
Why not just install the latest qiskit, perhaps in an env. Or you can just drop the provider package into the local qiskit dir

**Comment by yaelbh** [comment]
Ignis and Aer notebooks are up-to-date with respect to IBMQ, both here and in the community tutorials.
