### ISSUE TITLE
Fix Aer device noise simulation notebook

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-tutorials#752]
The notebook runs two simulators with the noise provided from the device, and the results are quite different from execution of the same circuit on the device. Then comes a paragraph of discussion, explaining where the difference comes from.

Something must have changed, probably the device's statement about its noise is more accurate. The simulation results are different when I run this notebook, from what they are in the repository, and match the results of the execution on the device. Therefore the histograms of the simulation results need to be updated, and the explanation paragraph needs to be updated or removed.

**Comment by nonhermitian** [comment]
Everything is being updated so will just include this as well.
