### ISSUE TITLE
move repetition code 

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-tutorials#763]
I think we should move https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/advanced/ignis/repetition_code.ipynb to qiskit-community-tutoiral.

**Comment by esobimpe** [comment]
Hi Jaygambetta, do you want to me work on this

**Comment by cristeam2** [comment]
> I think we should move https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/advanced/ignis/repetition_code.ipynb to qiskit-community-tutoiral.

This link is not available anymore

**Comment by omarcostahamido** [comment]
starting [Apr 25](https://github.com/Qiskit/qiskit-tutorials/tree/d93bcb14976b52d4ca4d8a6ad3cca0bfeccab72c) this repo received a new format. I believe this files, which can still be found/was last seen [here](https://github.com/Qiskit/qiskit-tutorials/blob/40af3da7aa86ce190d04f147daf46fbc893a1966/qiskit/advanced/ignis/8_repetition_code.ipynb) is in fact this file [here](https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/ignis/6_repetition_code.ipynb) now.
Should this be moved, an update to star_here.ipynb will also be needed.

**Comment by omarcostahamido** [comment]
oops! this issue was closed while I was writing this comment! damn... xD
