### ISSUE TITLE
3. Configure your IBM Q Provider::from qiskit import IBMQ

### ISSUE THREAD

**Issue by JonHill24** [Qiskit/qiskit-tutorials#779]
![err1](https://user-images.githubusercontent.com/38847726/63399142-4532a080-c395-11e9-937b-d22bc8393f75.jpeg)

### Informations

- **Qiskit version**: latest
- **Python version**: 3
- **Operating system**: ubuntu 18.04

### What is the current behavior?
(base) jon@jon-MacBookPro:~/Documents/Quantum/Qiskit/qiskit-tutorial$ from qiskit import IBMQ
from: can't read /var/mail/qiskit

### Steps to reproduce the problem
run tutorial to step 3 

### What is the expected behavior?
proceed to enter api key after this command

**Comment by aasfaw** [comment]
Hi @JonHill24.

The command

`from qiskit import IBMQ` 

is python code. You should be using it in your Python editor, not in the terminal directly.

The solution is to start python first by typing 
`python`
in your terminal.

Then, once you see the three arrows `>>>`, you can type the qiskit import code that you have shown above.

**Comment by nonhermitian** [comment]
Closing as the the answer from @aasfaw is indeed correct.
