### ISSUE TITLE
Pulse tutorial should use level 2 measurement

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-tutorials#785]
### What is the expected behavior?
Currently all contains of [calibrating a qubit](https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/advanced/ignis/1_calibrating_a_qubit.ipynb) tutorial use level1 measurement and the measured quantum state is expressed by normalized microwave amplitude. The behavior of `get_amplitude` helper function is unintelligible at first glance, and there are meaningless initial parameters to be set for Rabi curve fitting because measured microwave amplitude depends on backend hardware. Using level 2 measurement may improve this tutorial.

- Running Rabi Experiment
use level2 measurement and the vertical axis of Rabi figure should be replaced by <sigma_z>.

- Measuring the IQ Distribution from the 0 and 1 States
no change

- Running Rabi Experiment with Different Frequencies
use level2 measurement and the color axis of figure should be replaced by <sigma_z>

**Comment by nonhermitian** [comment]
This is no longer in scope as the tutorials should not require access to the devices
