### ISSUE TITLE
Remove calls to ibmqx4

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-tutorials#809]
The device is now retired.

**Comment by pedrorrivero** [comment]
Hi @nonhermitian I have submitted a draft pull request with this bug fixed  (#814 ). However this is my first pull request to qiskit and need some help with the final details. Could you lend me a hand? Thanks!

**Comment by pedrorrivero** [comment]
This issue should now be closed. Thanks for merging @nonhermitian
