### ISSUE TITLE
Qiskit tutorial format updates

### ISSUE THREAD

**Issue by JulesMurphy** [Qiskit/qiskit-tutorials#818]
@nonhermitian this is for you:

## Overall Qiskit Tutorials master page in IQX: 
- [ ] Name of overall tab should be “Qiskit tutorials”  instead of “1_start_here.i…”
- [ ] In the introductory paragraph, consider either linking the “educational material” link to something more specific, or reword the sentence so it is clear that the link takes a user back to the overall documentation and support page. 
- [ ] Since the tutorials within the sections are numbered, you do not need a number in front of the sections for Terra, Aer, Ignus, etc.
- [ ] Headers inside of the tutorials themselves should reference the subset of qiskit being used. Use the existing header for general tutorials, and create new banners for each of the other elements. That way, you don’t have to add “Qiskit Aer:” or “Qiskit Aqua:” etc. at the beginning of each tutorial title  (Feel free to open a design issue and we can help with it)

### Getting started with Qiskit section
5. Using the Transpiler  
- [ ] Title should read “Circuit Rewriting using the Transpilar” to match the name of the actual notebook and provide more clarity to users who may not know what a transpiler is 
- [ ] Table of contents should be brought up higher on the page to be consistent with other notebooks 
6. Jupyter Tools  
- [ ] Qiskit import cell should be after table of contents 
7. Summary of quantum operations
- [ ] Needs a table of contents

### Terra section
1. Advanced circuits 
- [ ] Title inside notebook should read “Advanced circuits” instead of “Terra 0.8 - Circuit API updates” 
- [ ] Table of contents should follow format of other notebooks
2. Operators overview  
- [ ] Title missing. Should replace “Introduction” with “Operations overview” 
- [ ] Missing a table of contents
3. Advanced circuit visualization 
- [ ] Title does match link title. Change “Visualizing a Quantum Circuit” with “Advanced Circuit Visualization” 
- [ ] Missing a table of contents
4. Transpiler passes and passmanager 
- [ ] Introduction cell should be removed and the title and introductory text combined 
- [ ] Missing a table of contents
5. Pulse schedules 
- [ ] Missing a table of contents
6. Creating a new provider 
- [ ] Introduction text can be combined with title area - Missing a table of contents 

### Aer section
1. Aer provider 
- [ ] Title inside of notebook does not match link title 
- [ ] Introduction text can be combined with title cell 
- [ ] Missing a table of contents

2. Device noise simulation 
- [ ] Title inside of notebook does not match link title 
- [ ] Introduction text can be combined with title cell 
- [ ] Missing a table of contents

3. Building noise models
- [ ] Introduction text can be combined with title cell
- [ ] Missing a table of contents

4. Custom gate noise
- [ ] Title inside of notebook does not match link title 
- [ ] Introduction text can be combined with title cell 
- [ ] Missing a table of contents

5. Noise transformations
- [ ] Introduction text can be combined with title cell 
- [ ] Missing a table of contents

6. Extended stabilizer tutorial
- [ ] Title inside of notebook does not match link title
- [ ] Introduction text can be combined with title cell
- [ ] Missing a table of contents

7. Matrix Product State simulator
- [ ] Title inside of notebook does not match link title
- [ ] Introduction text can be combined with title cell 
- [ ] Missing a table of contents

### Ignis
1. Calibrating a qubit
- [ ] Missing description and a table of contents
2. Hamiltonian and gate characterizations 
- [ ] Not sure why title is in italics 
- [ ] Missing a table of contents
3. Relaxation and decoherence
- [ ] Not sure why title is in italics
- [ ] Missing a table of contents
4. Measurement error mitigation
- [ ] Introduction text can be combined with title cell 
- [ ] Missing a table of contents
5. Randomized benchmarking:
a. Randomized benchmarking  
- [ ] Missing a table of contents
b. Interleaved RB 
- [ ] Missing a table of contents
c. Purity RB 
- [ ] Missing a table of contents
6. Tomography:
a. Quantum state tomography
- [ ] Missing a table of contents
b. Quantum process tomography  
- [ ] Missing a table of contents
7. Quantum volume  
- [ ] Title size does not match other tutorials - Missing a table of contents
8. Repetition Code
- [ ] Missing a table of contents
9. Logging   
- [ ] Missing a table of contents -

### Aqua
- [ ] Not sure why this section is not numbered the same way as the previous sections 

Amplitude Estimation 
- [ ] Not sure why name is italicized
- [ ] Missing table of contents
HHL  
- [ ] Title does not match link title 
- [ ] de-italicize title 
- [ ] Missing table of contents
Creating an Aqua algorithm 
- [ ] Title does not match link title 
- [ ] de-italicize title - Missing table of contents  

5.1 Qiskit Artificial Intelligence
Qiskit AI  	
- [ ] Does this need to be its own page, or could the links be brought up a level?
5.2 Qiskit Chemistry
Qiskit Chemistry  		
- [ ] Does this need to be its own page, or could the links be brought up a level?
5.3 Qiskit Finance
Qiskit Finance  		
- [ ] De-italicize title 		
- [ ] Does this need to be its own page, or could the links be brought up a level?
5.4 Qiskit Optimization
Qiskit Optimization  	
- [ ] Does this need to be its own page, or could the links be brought up a level?

**Comment by nonhermitian** [comment]
I think all of this is taken care of with the move to docs building the tutorials.  The build system is quite strict about the styling now.
