### ISSUE TITLE
Include reference to optional visualization requirements

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-tutorials#819]
According to Qiskit's installation requirements: ***"There are optional dependencies that are required to use all the visualization functions available in Qiskit"***. These can be installed by running `pip install qiskit-terra[visualization]`.

During the tutorials, these optional features are sometimes required but never referenced, which may lead to issues for people new to the software.

**Comment by nonhermitian** [comment]
Now that the tutorials are rendered in the docs, this is not needed anymore.  The main docs discuss the need for the visualization add on: https://qiskit.org/documentation/install.html#install
