### ISSUE TITLE
Paragraph repetition in ./qiskit/fundamentals/2_plotting_data_in_qiskit

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-tutorials#820]
### Paragraph

When using ***[any of the state plotting functions / the `plot_bloch_vector` function]*** it returns a `matplotlib.Figure` for the rendered visualization. Jupyter notebooks understand this return type and render it for us in this tutorial, but when running outside of Jupyter you do not have this feature automatically. However, the `matplotlib.Figure` class natively has methods to both display and save the visualization. You can call `.show()` on the returned object to open the image in a new window (assuming your configured matplotlib backend is interactive). Or alternatively you can call `.savefig('out.png')` to save the figure to `out.png` in the current working directory. The `savefig()` method takes a path so you can adjust the location and filename where you're saving the output.

### Occurances

- Using the output from state plotting functions
- Adjusting the output from plot_bloch_vector()

**Comment by nonhermitian** [comment]
Not sure I understand the issue here as the tutorials are running inside of notebooks.  Of course there is differences when bringing up figures outside of the notebook context, but such discussion is not needed here.  Indeed, the ability to automatically inline images is one of the benefits of using notebooks in the first place.

**Comment by pedrorrivero** [comment]
Hi @nonhermitian, thanks for your reply.

What I meant when I opened this issue is that the cited paragraph was written twice in the tutorial in almost identical fashion. Currently I believe it might even be repeated three times. This is redundant information which makes the tutorial unnecessarily longer; it has nothing to do with the content of the paragraph though.

You can check this on your own by searching for the sentence: *"for the rendered visualization. Jupyter notebooks understand this return type and render it for us in this tutorial, but when running outside of Jupyter you do not have this feature automatically"*. You will find three occurrences. Alternatively, you can look for them in the sections that I point to in my original post.

Also, this is now under `./tutorials/circuits/`.
