### ISSUE TITLE
Explain how to set a default render configuration in ./qiskit/advanced/terra/3_advanced_circuit_visualization.ipynb

### ISSUE THREAD

**Issue by pedrorrivero** [Qiskit/qiskit-tutorials#826]
### What is the expected behavior?

Include a note similar to that in './qiskit/fundamentals/1_getting_started_with_qiskit.ipynb' with expanded information on how to set a default configuration.

**Comment by nonhermitian** [comment]
Now that the tutorials are rendered in the main qiskit docs, this is now something that can be addressed there.  Many thanks for bringing it up!
