### ISSUE TITLE
Terra Advanced Circuits notebook, qiskit can't find an expected JSON file

### ISSUE THREAD

**Issue by dwvisser** [Qiskit/qiskit-tutorials#836]
### Informations

- **Qiskit version**: 0.13.0
- **Python version**: 3.6.8
- **Operating system**: Linux Mint 19.2 Cinnamon

### What is the current behavior?

This line in `qiskit/advanced/terra/1_advanced_circuits.ipynb` generates an error:

```python
compiled_circuits = transpile(qcs, backend=FakeTokyo())
```

Here's the error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/dale/VirtualEnvs/qiskit_trial/lib/python3.6/site-packages/qiskit/test/mock/props_tokyo.json'
```

### Steps to reproduce the problem

Run the notebook page.

### What is the expected behavior?
No error, as in the current snapshot notebook on GitHub, which was running qiskit v0.9.0

### Suggested solutions
Not sure. It looks like the JSON file was removed from the `qiskit` repository at some point?

**Comment by ajavadia** [comment]
this was a packaging issue. it will work if you install from source. 
this PR should fix the issue: https://github.com/Qiskit/qiskit-terra/pull/3445

**Comment by dwvisser** [comment]
Thank you! 😃 Looking at the PR, I'll probably just copy the JSON file from the "terra" project where its needed. I'm really just wanting to understand all the tutorial material, and run it for myself as much as possible. BTW, are there any plans to get https://hub.docker.com/r/qiskit/qiskit-tutorial up to date with the current cloud authentication API?

**Comment by nonhermitian** [comment]
Docker does not have the security needed for token passing to the api so its use is discontinued

**Comment by nonhermitian** [comment]
Closing this as no longer needed.
