### ISSUE TITLE
AQT tutorial needs statement of prerequisites

### ISSUE THREAD

**Issue by luukament** [Qiskit/qiskit-tutorials#854]
### What is the expected behavior?
It would be great if the AQT tutorial (https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/advanced/terra/7_different_qubit_technologies.ipynb) starts with a sentence saying "The AQT provider needs to be installed first, using: pip install qiskit-aqt-provider." and a description of who can get a token, and how to get one.

**Comment by nonhermitian** [comment]
We can give the link and the statement. However who can get a token, and for what devices / simulators, is up to AQT. We currently do not have access to the device ourselves with the new AQT api.

**Comment by luukament** [comment]
Does AQT have a webpage or something that describes their policy & process? Would be nice to refer the users to a specific place.

**Comment by jaygambetta** [comment]
@nonhermitian we should close this issue or move this to the community tutorials.

**Comment by nonhermitian** [comment]
I am fine moving this.  However, it is probably best once the repo lands in its new home.

**Comment by nonhermitian** [comment]
Closing this as I am going to move the tutorial into community.
