### ISSUE TITLE
Renaming Qiskit Notebooks does not refresh the name on the Notebook tab.

### ISSUE THREAD

**Issue by robertloredo** [Qiskit/qiskit-tutorials#855]
### System Information
Running on IBMQ Experience,

    Qiskit | 0.14.0
    Terra | 0.11.0
    Aer | 0.3.4
    Ignis | 0.2.0
    Aqua | 0.6.1
    IBM Q Provider | 0.4.4
    Python | 3.7.3 \| packaged by conda-forge \| (default, Dec  6 2019, 08:54:18)  [GCC 7.3.0]
    OS | Linux
    CPUs | 8    
    Memory (Gb) | 31.409332275390625
    Wed Jan 01 17:01:54 2020 UTC

### What is the current behavior?

When creating a new Qiskit Notebook, the tab is initialized to `Untitled.ipynb`, when renaming the notebook, the tab is not updated. Even after a refresh of the page. 

Also, the notebook name does not get updated in the list view of notebooks unless you refresh  the notebook list page.  

### Steps to reproduce the problem
1. Create a new page (autogenerated as Untitled)
2. Rename the page to anything (HelloWorld)
3. Click Rename button to rename page.

### What is the expected behavior?
1. The Notebook tab should auto update from Untitled.ipynb to HelloWorld.ipynb)
2. Notebook list page should auto refresh when returning back to the list page.

### Actual behavior
1. The Notebook tab does not update. 
2. The Notebook list does not update. I need to refresh the page to update the name. 
3. When I click on the Untitled.ipynb page from the list (before refreshing), the Untitled.ipynb page returns a 404 Page not found error. Assuming this is an indication that the page name was updated and the old one does not exist. 

### Suggested solutions

**Comment by nonhermitian** [comment]
This is an issue for the internal IQX notebook team, and cannot be addressed here.
