### ISSUE TITLE
Renderer behaviour doesn't match description in terra/3_advanced_circuit_visualization.ipynb.

### ISSUE THREAD

**Issue by dlyongemallo** [Qiskit/qiskit-tutorials#858]
The notebook says:
> You can either call `print()` on the circuit, or call the `draw()` method on the object. This will render a ASCII art version of the circuit diagram. [snip] There are two alternative output renderers for the quantum circuit. One uses matplotlib, and the other uses LaTeX, which leverages the qcircuit package. These can be specified by using `mpl` and `latex` values for the output `kwarg` on the `draw()` method. [snip] `'text'`(the default) returns a TextDrawer object...

However, the call to `circuit.draw()` with no parameters actually draws a matplotlib figure. It seems that at some point, the default was changed from `text` to `mpl`. The notebook should be updated to reflect this.

**Comment by nonhermitian** [comment]
The default is still text unless otherwise set in the qiskit configrc file. It is set to mpl by defult using this file on the IQX

**Comment by dlyongemallo** [comment]
Ah, okay. In that case, a note should probably be added just above or below the `circuit.draw()` call to make this less confusing.

**Comment by nonhermitian** [comment]
I agree that this is confusing, but it is likely something to address in the Qiskit docs (it seems not to be there) and link to it there.

**Comment by nonhermitian** [comment]
Closing as the main Qiskit docs is the place to do this.  Will make an issue there.
