### ISSUE TITLE
Broken link in Aqua tutorial

### ISSUE THREAD

**Issue by sorin-bolos** [Qiskit/qiskit-tutorials#888]
In this tutorial "Qiskit Aqua: qGANs for Loading Random Distributions" there is a  link on this line:

"How to use a trained qGAN in an application, i.e., pricing of financial derivatives, is illustrated here: qGAN Option Pricing." 

If you right-click and chose "Open link in new tab" it leads to a blank page that only  says "Unknown type"

**Comment by nonhermitian** [comment]
I think this is no longer an issue.
