### ISSUE TITLE
Some (legacy) tutorials need minor correction

### ISSUE THREAD

**Issue by Albert65** [Qiskit/qiskit-tutorials#911]
### Informations

- **Qiskit version**: 0.19.1
- **Python version**: 3.7
- **Operating system**: OSX Catalina

### What is the current behavior?

Wrong path to import

### Steps to reproduce the problem

from qiskit.optimization.ising import XXX 

### What is the expected behavior?

XXX package path should be resolved

### Suggested solutions

Adding "applications" sub-folder into the path

from qiskit.optimization.applications.ising import XXX

**Comment by nonhermitian** [comment]
They are legacy because they are not up to date, take too long to run, or contact hardware. The authors need to go back and modify or create new ones

**Comment by nonhermitian** [comment]
Closing as issue has become stale.  Please reopen if there is anything else needed.
