### ISSUE TITLE
Counting the number of CNOTs in a QuantumCircuit?

### ISSUE THREAD

**Issue by AdrianTanTeckKeng** [Qiskit/qiskit-tutorials#914]
Is there a way to obtain the number of CNOTs in a quantum circuit. The tutorial over here https://qiskit.org/textbook/ch-applications/hhl_tutorial.html suggests one can use result['circuit_info']['operations']['cx'] but it seems changes were made and the method doesn't work anymore.

**Comment by nonhermitian** [comment]
Circuit.count_ops()[‘cx’]

**Comment by aasfaw** [comment]
Tagging @frankharkins here
