### ISSUE TITLE
Broken link in the contribution guideline

### ISSUE THREAD

**Issue by ougni** [Qiskit/qiskit-tutorials#923]
In the contribution guideline, it is noted that the new notebooks should be placed in the "community" section. 
I do not see any community section and the [link](https://github.com/Qiskit/qiskit-tutorials/blob/master/.github/community) also seems to be broken. I'm referring to [this](https://github.com/Qiskit/qiskit-tutorials/blob/master/.github/CONTRIBUTING.md) file.

**Comment by nonhermitian** [comment]
Closing.
