### ISSUE TITLE
4_pulse_scheduler.ipynb legacy tutorial seems incomplete

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-tutorials#939]
There is a section that says "Todo" that should be completed before it goes into the docs.  Also, there is an unused import of `IBMQ` that should be removed as this is not allowed in the docs build, and of course because it is not needed.

**Comment by Eric-Arellano** [comment]
This was fixed some time ago in https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/circuits_advanced/07_pulse_scheduler.ipynb.
