### ISSUE TITLE
asian_barrier_spread_pricing.ipynb legacy tutorial does not execute within the desired runtime limits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-tutorials#941]
The "Evaluate Expected Payoff" section of the asian pricing tutorial takes a long time to run, and thus the tutorial cannot be included in the docs because of this.  Thus the runtime needs to be reduced for inclusion.

**Comment by Eric-Arellano** [comment]
This tutorial no longer exists in this repo.
