### ISSUE TITLE
Where to put amplitude_estimation and generating_random_variates tutorials

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-tutorials#948]
I am not sure what category to put the amplitude estimation and random variates under. @stefan-woerner do you have any thoughts on this?

**Comment by wagnersj** [comment]
I'm curious about this issue. It looks like there is no longer a tutorial on amplitude estimation in this repo or on the Qiskit Web site. Was it moved somewhere else or does it no longer exist? I found this one: [https://github.com/stefan-woerner/qiskit-tutorials/blob/0697eae042dab907b19a6b6cb267b7829d022379/qiskit/aqua/general/amplitude_estimation.ipynb](https://github.com/stefan-woerner/qiskit-tutorials/blob/0697eae042dab907b19a6b6cb267b7829d022379/qiskit/aqua/general/amplitude_estimation.ipynb)

**Comment by Eric-Arellano** [comment]
Yeah, this issue is stale @wagnersj. Thanks.
