### ISSUE TITLE
6a_state_tomography.ipynb legacy tutorial raises error

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-tutorials#950]
On Qiskit 0.19.6 this tutorial raises the following exception:

SolverError: Either candidate conic solvers (['ECOS']) do not support the cones output by the problem (SOC, Zero, PSD), or there are not enough constraints in the problem.

**Comment by ShellyGarion** [comment]
this issue was handled in #1026

**Comment by ShellyGarion** [comment]
this issue was handled in #1026

**Comment by Eric-Arellano** [comment]
This tutorial no longer exists in this repo -- and sounds like it was fixed in #1026
