### ISSUE TITLE
6b_process_tomography.ipynb legacy tutorial raises exception

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-tutorials#951]
On Qiskit 0.19.6, this tutorial raises the following exception:

QiskitError: 'channel is not completely-positive'

**Comment by brosand** [comment]
I'm also experiencing this issue, are there any updates? The error is generated when I try to obtain the process fidelity (but not the state fidelity) from the tomography data

**Comment by ShellyGarion** [comment]
this issue was handled in #1026
