### ISSUE TITLE
10_discriminator.ipynb legacy tutorial calls IQX and thus cannot be included in tutorials

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-tutorials#952]
The discrimination tutorial needs to call the IQX in order to execute.  This call needs to be removed in order for this tutorial to be included in the docs build.  I think that this is actually not possible, but would like to have this verified.  Because loosing material is never good, perhaps there is another place for it? @ajavadia

**Comment by Eric-Arellano** [comment]
This tutorial no longer exists in this repo.
