### ISSUE TITLE
allow QuantumChannel as target in process_fidelity? terra#4694

### ISSUE THREAD

**Issue by qci-amos** [Qiskit/qiskit-tutorials#967]
I created this issue:
https://github.com/Qiskit/qiskit-terra/issues/4694
but perhaps I should have created it here instead.

### Informations

- **Qiskit version**:
latest
- **Python version**:
- **Operating system**:

### What is the current behavior?

I believe that this line in the process tomography tutorial:
```
print('fit fidelity (process):', np.real(process_fidelity(choi_ideal, choi_lstsq.data, require_cptp=False)))
```
computes an incorrect fidelity (see the terra issue for details)

https://github.com/Qiskit/qiskit-tutorials/blob/master/legacy_tutorials/ignis/6b_process_tomography.ipynb

### Steps to reproduce the problem

If you run it as-is

### What is the expected behavior?

The correct process fidelity

It might be nice to see `average_gate_fidelity` in there too

### Suggested solutions

* don't pass `.data` to process fidelity since that appears to bypass `isinstance` checks
* maybe you could pass the ideal channel to `target` and allow it to be converted to an `Operator`? unclear to me if that's correct or not.
* add support for a noisy `target` channel to `process_fidelity`

**Comment by rafal-pracht** [comment]
The link to tutorial is not working. Could you give me the correct one?

**Comment by qci-amos** [comment]
@rafal-pracht this looks like the successor notebook: https://github.com/Qiskit/qiskit-tutorials/blob/master/tutorials/noise/8_tomography.ipynb

it looks like the notebook has been rewritten and the specific concern is no longer applicable.

By reading its docstring, it looks like `process_fidelity` now supports the feature I was requesting, so I closed the terra issue too.
