### ISSUE TITLE
1_getting_started_with_qiskit.ipynb should improve markdown for rst conversion

### ISSUE THREAD

**Issue by ksouji** [Qiskit/qiskit-tutorials#975]
## Target file
tutorials/circuits/1_getting_started_with_qiskit.ipynb.

### 1. rst constraints
Markdown can use emphasis and link at the same time, but rst cannot. It should be modified to a notation that can be converted to rst.    
The following is the converted statement.
>  The fundamental unit of Qiskit is the \*\*quantum circuit\*\*. 

In this case, it is better to remove the emphasis.

### 2. Markdown notation when using List
When using List, it is necessary to insert a line break before and after each line. Otherwise, the symbol "*" will be treated as a string during rst conversion and merged into a single line.
The following is the converted statement.
> To create such a state, we start with a three-qubit quantum register. By default, each qubit in the register is initialized to |0⟩. To make the GHZ state, we apply the following gates: \* A Hadamard gate H on qubit 0, which puts it into the superposition state (|0⟩+|1⟩)/2–√. \* A controlled-Not operation (CX) between qubit 0 and qubit 1. \* A controlled-Not operation between qubit 0 and qubit 2.

## Note

Some other files have similar issues. Therefore, other files also need to be checked and modified.

**Comment by ksouji** [comment]
I think the following sentence is also wrong. Maybe the last letter is ρ.

> Below, we use the visualization function to plot the real and imaginary components of the state density matrix $ ho$.

Should this Issues category be a bug?

**Comment by kimaranaicker** [comment]
Hi @ksouji, can I work on fixing the syntax issue here?

**Comment by ksouji** [comment]
> Hi @ksouji, can I work on fixing the syntax issue here?

@kimaranaicker , 
I asked the administrator. It's a good idea to create a new Issue if you get some Syntax errors. In that case, it may be better not to specify the file name in the Issue title.
If you are targeting multiple files or files different from this issue, please create a new issue.
