### ISSUE TITLE
6_examples_max_cut_and_tsp.ipynb sphinx math expression not rendered

### ISSUE THREAD

**Issue by ivanightingale** [Qiskit/qiskit-tutorials#978]
## Description
A math expression in 6_examples_max_cut_and_tsp.ipynb is not rendered properly on the webpage:
![image](https://user-images.githubusercontent.com/31260816/89312607-760ef280-d645-11ea-921d-ee80cdaa7cc3.png)

#### Browsers used
Microsoft Edge, Google Chrome

#### Operating systems used
Windows 10, Ubuntu 20.04 LTS

**Comment by tgag17** [comment]
Hi! Can I work on this?

**Comment by divshacker** [comment]
Hey @ivanightingale now I can't see this problem on website. Maybe someone have fixed this issue already. If the problem is resolved according to you then please close this issue. 
Thank You

**Comment by divshacker** [comment]
@nonhermitian  I think You can close this issue
