### ISSUE TITLE
Labelling error in Qiskit tutorials >> Circuit Tutorials 

### ISSUE THREAD

**Issue by abhishekjay** [Qiskit/qiskit-tutorials#987]
I noticed a small **labeling error** in the **Qiskit tutorials documentation**. The exact location is _**Tutorials >> Circuit Tutorials >> Getting started with Qiskit**_ page. 

  Here, under the **Visualize Circuit** header, a system of _n_ qubits is mentioned. An _n_ qubit system has qubits labelled from _Q0 to Qn-1_. Instead, the tensor product that is displayed, has qubits ranging from _Q0 to Qn_, thereby denoting an _n+1_  qubit system.

The labelling of the qubits is to be changed to: _Q0 to Qn-1_.

**Comment by brunormzg** [comment]
Hello @abhishekjay, I would like to work on this issue. Is it ok if I give it a go?

**Comment by abhishekjay** [comment]
Sure! All the best!
