### ISSUE TITLE
Some ipynb files should improve markdown for rst conversion

### ISSUE THREAD

**Issue by sik55** [Qiskit/qiskit-tutorials#992]
# Summary

This issue deals with multiple issues with multiple files.

## 1. circuits/3_summary_of_quantum_operations.ipynb

When using List, it is necessary to insert a line break before and after each line. Otherwise, the symbol "*" or "-" will be treated as a string during rst conversion and merged into a single line.

Display on rst:

![image](https://user-images.githubusercontent.com/32782726/89701038-74f40300-d96e-11ea-8fb1-9b8fc8160546.png)

![image](https://user-images.githubusercontent.com/32782726/89701019-4d9d3600-d96e-11ea-8dc7-d22aad914da2.png)

Source strings on git:

![image](https://user-images.githubusercontent.com/32782726/89701062-b5538100-d96e-11ea-9eff-006bc1fa9d44.png)

## 2. circuits_advanced/2_operators_overview.ipynb

This seems to be Typo. 

my -> may

![image](https://user-images.githubusercontent.com/32782726/89701225-b46f1f00-d96f-11ea-8c75-0c30e9e1d1ed.png)

## 3. circuits_advanced/4_transpiler_passes_and_passmanager.ipynb

There is an extra ")".  

![image](https://user-images.githubusercontent.com/32782726/89701351-0b292880-d971-11ea-880d-3441bb57327a.png)

## 4. optimization/6_examples_max_cut_and_tsp.ipynb

It is the same problem as No1. Here is a list of numbers.

![image](https://user-images.githubusercontent.com/32782726/89701410-b76b0f00-d971-11ea-9dee-16a8b8cf0e8c.png)

## 5. pulse/4_adding_measurements.ipynb

+ There are two problems here.
    + Markdown is displayed.
    + There is Typo. disciminated -> discriminated

![image](https://user-images.githubusercontent.com/32782726/89701540-dddd7a00-d972-11ea-886a-97efe5181bfc.png)

## 6. pulse/5_gathering_system_information.ipynb

Markdown can use emphasis and link at the same time, but rst cannot.  
In this case, it is better to remove the emphasis.

Display on rst:

![image](https://user-images.githubusercontent.com/32782726/89701613-93103200-d973-11ea-9d6b-e813b651f347.png)

## 7. pulse/8_pulse_simulator_backend_model.ipynb

The display on rst is broken.  
Improvement is needed.

raw source:

![image](https://user-images.githubusercontent.com/32782726/89701672-1893e200-d974-11ea-8da5-f14e16bf2d8f.png)

Display on rst:

![image](https://user-images.githubusercontent.com/32782726/89701652-e1bdcc00-d973-11ea-8c3c-30c04c5bfb78.png)

**Comment by souji555** [comment]
+ Already resolved
  + 4.optimization / 6_examples_max_cut_and_tsp.ipynb  
  + 5.pulse / 4_adding_measurements.ipynb --There is Typo. Disciminated-> discriminated
+ Remaining issue
  + 7.pulse / 8_pulse_simulator_backend_model.ipynb

**Comment by Eric-Arellano** [comment]
Looks like @divshacker fixed the remaining issues in https://github.com/Qiskit/qiskit-tutorials/pull/1149. Thanks! And thanks @sik55 for reporting the issues!
