### ISSUE TITLE
Qiskit tutorials being inside the documentation reduce it's outreach

### ISSUE THREAD

**Issue by rochisha0** [Qiskit/qiskit-tutorials#993]
### What is the current behavior?
Whenever we search for Qiskit tutorials on Google, there is no sign of Qiskit tutorials page.

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/45593458/89718909-aefded00-d9e0-11ea-80c3-61c9351ed0b5.png)

### What is the expected behavior?

Qiskit tutorials (the documentation page) should be the first thing to appear.

**Comment by nonhermitian** [comment]
The first link that I see is qiskit.org which has links to tutorials. I am not sure what is wrong with this. The tutorials are part of the docs, which includes the api, so that there is a single source of information on using Qiskit.

**Comment by rochisha0** [comment]
It is not that easily accessible through browser Searches as Qiskit Textbook. According to me, the first thing to pop up should be direct to Qiskit tutorials. It becomes harder to navigate for the person who doesn't know tutorials exist as they never show up directly in browser searches.

**Comment by divshacker** [comment]
If we search "qiskit documentation" then it is working fine. Showing Documentation link as first link. I think searching documentation instead of tutorials solves the problem. what you say @rochisha0

**Comment by Eric-Arellano** [comment]
Two updates:

1. On google, my first result for `qiskit tutorials` is the correct link https://qiskit.org/documentation/tutorials.html
2. This repo is being archived very soon and the tutorials are moving to Qiskit Terra.

So, this can be closed.
